import 'package:bitnan/@share/constants/language.constant.dart';

const Map<String, String> en_US = {
  KAppName: 'Bitback',
  KSelectFund: 'Chọn nguồn tiền',
  KSelectFundMoney: 'Nguồn tiền',
  KRewardWallet: 'Wallet Reward',
  KTrustPayWallet: 'Wallet Bitback',
  KChargeMore: ' more',
  KAddAssociate: 'More links',
  KDigitalWallet: 'e-Wallet',
  KSurplus: 'Surplus',
  kLoading: 'Processing...',
  kHome: 'Home',
  kPlay: 'Play',
  kHistory: 'History',
  kHistoryOnChain: 'On-Chain',
  kHistoryOffChain: 'Off-Chain',
  kHistoryPayment: 'Payment',
  kHistoryReferFrom: 'Introduction from',
  kHistoryReferBy: 'Introduction by',
  kHistoryKYC: 'KYC',
  kAbout: 'Introduce',
  kPerson: 'Quản lý tài khoản',
  kHello: 'Hello %s!',
  kPreMoney: '≈',
  kBTCFormat: '%s BTC',
  kSATFormat: '%s SAT',
  kMessageSuccess: 'Your transaction is being processed',
  kVNDC: 'VNDC',
  kVND: 'VND',
  kMoneyFormat: '%s VNDC',
  kConfirmation: 'Transaction confirmation',
  kPromotionBuy: 'Buy deals',
  kFunds: 'Funds',
  kInitialMoney: 'Initial money',
  kTransactionFee: 'Transaction fee',
  kDiscount: 'Discount',
  kPayment: 'Payment amount',
  kNeedPayment: 'Amount to be temporarily calculated',
  kExchange: 'Exchange',
  kConfirm: 'Confirm',
  kActivated: 'Activated',
  kAccountActivated: 'Chưa kích hoạt',
  kAccountIdentification: 'Chưa định danh',
  kAccountReview: 'Chờ duyệt',
  kAccountReject: 'Yêu cầu định danh bị từ chối',
  kUpdateProfile: 'Update successful',
  kTextInputPhone: 'Enter your phone number',
  kInputPhone: 'Phone number',
  kPhoneNumber: 'Phone number',
  kEditEmail: 'Update email',
  kVerifyEmail: 'Email verification',
  kChangeEmail: 'Update email',
  kContinue: 'Continue',
  kAllStores: 'All stores',
  kDirect: 'Direct',
  kDistanceFormat: '%s km',
  kGoHome: 'Back Home',
  kLetPromotion: 'View offers',
  kMessageSuccessStart: 'You Just Used ',
  kMessageSuccessEnd: ' to buy preferential vouchers ',
  kVoucherSuccess: 'Successful purchase offer',
  kConfirmPhone: 'Verify phone number',
  kInputOtp: 'Enter the OTP that was sent to your phone number',
  kResendOtp: 'Resend code',
  kResendOtpWithNum: 'Resend code (%s)',
  kReceiverSat: 'Receive Satoshi',
  kChangePhoneNumber: 'Change phone number',
  kLoginInfo: 'Login information',
  kFullName: 'Your name',
  kSignUp: 'Sign up',
  kChangePassSuccess: 'Password successfully changed',
  kGiveCoinSuccess: 'Congratulations you have received',
  kSignUpSuccess: 'Account registration \nsuccessful',
  kSendInfoSuccess: 'Successful submission of information',
  kIntoHome: 'Go to home',
  kUnderstood: 'Understood',
  kWatchDetail: 'See details',
  kAgree: 'Agree',
  kMessageSendInfoSuccess: 'Bitback system is validating your identity.',
  kMessageChangePassSuccess:
      'Please change your password regularly to \nincrease the security of your account',
  kReward: 'Reward',
  kBalance: 'Surplus',
  kEarnSAT: 'Earn Satoshi',
  kOfferChanged: 'Ưu đãi',
  kTransfer: 'Redeem reward',
  kTransferMinAmount: 'Minimum: ',
  kTransferMaxAmount: 'Tối đa: ',
  kTransferTransactionFee: 'Transaction fee: ',
  kAvailableBalances: 'Available balances',
  kRecharge: 'Deposit',
  kWithdrawal: 'Withdraw',
  kTransfersMoney: 'Exchange',
  kQRCode: 'Code QR',
  kVerifyDescription:
      'Xác minh thông tin và liên kết tài khoản ngân hàng để bảo mật và thực hiện giao dịch',
  kVerifyTitle: 'Xác thực thông tin cá nhân',
  kVerifyBank: 'Liên kết ngân hàng',
  kVerifyNow: 'Verify now',
  kHotVoucher: 'Ưu đãi bán chạy',
  kMore: 'Xem thêm',
  kPriceSale: '-%s%',
  kOutstandingBrand: 'Các thương hiệu',
  kHotNews: 'Bản tin nóng hổi',
  kServices: 'Dịch vụ',
  kHide: 'Ẩn bớt',
  kCurrentDeal: 'Ưu đãi đang diễn ra',
  kSeeAll: 'See more',
  kHasSat: 'Your balance',
  kContactInfo: 'Thông tin liên hệ',
  kStore: 'Cửa hàng',
  kUseFaceID: 'Sử dụng Face ID',
  kLater: 'Later',
  kUseFaceIDAnotherTime:
      'Đăng ký sử dụng Face ID \ncho lần đăng nhập tiếp theo',
  kSeeAllAddress: 'Xem tất cả địa điểm (%s)',
  kCreatePass: 'Create password',
  kNewPass: 'New password',
  kConfirmPass: 'Confirm password',
  kTypePassword: 'Nhập mật khẩu',
  kFaceAuth: 'Xác thực gương mặt',
  kNotify: 'Notification',
  kNotifyEmpty: 'Không có thông báo',
  kNotifyNew: 'Khi có tin mới, chúng tôi sẽ\nthông báo đến bạn ngay',
  kEkycIdentifier: 'Định danh eKYC',
  kTransferCoin: 'Chuyển Coins',
  kTransfersOffline: 'Thanh toán tại điểm thanh toán',
  kBarcodeTitle: 'Cung cấp mã này cho thu ngân khi thanh toán',
  kExpiration: 'Hiệu lực đến hết %s - ',
  kExpired: 'Hết hạn',
  kTitlePromotion: 'Bạn sẽ nhận được',
  kTerm: 'Điều kiện & Điều khoản',
  kLocateUse: 'Địa điểm áp dụng',
  kHelloDot: 'Hello, %s!',
  kInputPass: 'Password',
  kForgetPass: 'Forgot password?',
  kWithDrawTitle: 'Giao dịch đang được xử lý',
  kWithDrawMgs: 'VNDC sẽ được chuyển vào ví ONUS.',
  kWithDrawFail: 'Rất tiếc, giao dịch thất bại',
  kTryAgainWithDraw: 'Oops! Transaction failed.',
  kNotMe: 'Pleasse, try again.',
  kVoucher: 'Ưu đãi',
  kCreateNewPass: 'Tạo mật khẩu mới',
  kTitleLinkBank: 'Liên kết thẻ %s',
  kDescriptionLinkBankStart: 'Xác nhận liên kết thẻ của ngân hàng ',
  kDescriptionLinkBankEnd: ' vào Ví Bitback để sử dụng cho các giao dịch.',
  kConditionLink: 'Điều kiện để liên kết thẻ:',
  kFirstNotifyConditionStart: 'Thẻ đã bật chức năng ',
  kFirstNotifyConditionEnd: 'Thanh toán trực tuyến.',
  kSecondNotifyConditionStart: 'Nạp ít nhất ',
  kSecondNotifyConditionCenter: '%s ₫ vào ví ',
  kSecondNotifyConditionEnd: 'để đảm bảo tài khoản thẻ còn hoạt động.',
  kEffective: 'Hiệu \n lực',
  kDateFormat: '--/--',
  kSelectBank: 'Chọn ngân hàng liên kết',
  kMessageTypeBank: 'Nhập tên hoặc mã ngân hàng',
  kMessageTypeCardInfo: 'Nhập thông tin thẻ',
  kTypeCardNum: 'Nhập số thẻ',
  kEffectiveDateInfoCard: 'Ngày hiệu lực (MM/YY)',
  kTypeMoney: 'Nhập số tiền',
  kCardInfoMess: 'Bạn cần nạp tối thiểu 10,000 ₫ để thẻ được liên kết.',
  kLink: 'Liên kết',
  kTakeIdentityPapers: 'Chụp hình giấy tờ tùy thân',
  kTakeIdentity:
      'Bạn cần chụp hình mặt trước và sau của CMND hoặc CCCD hoặc Hộ chiếu',
  kNotProvided: 'Chưa cung cấp',
  kTakePicture: 'Chụp hình',
  kTakeFaceVideo: 'Quay video khuôn mặt',
  kVerifyFace: 'Bạn cần xác thực khuôn mặt của bạn cùng với giấy tờ tùy thân',
  kTakeVideo: 'Quay video',
  kSendIdentity: 'Gửi định danh',
  kFlow: 'Theo',
  kPolicy: ' quy định của NHNN ',
  kRequestIdentity: ', tài khoản ví phải được định danh trước khi sử dụng',
  kSelfIdentity: 'Sử dụng giấy tờ tùy thân hợp lệ của chính bạn',
  kInsideCamera: 'Phải đặt thẻ trong khung camera',
  kNotPhotoIdentity: 'Không sử dụng bản sao của giấy tờ tùy thân',
  kIdentityEKYC: 'Định danh tài khoản (eKYC)',
  kStart: 'Bắt đầu',
  kScanQrCode: 'Quét mã',
  kScanCode: 'Thanh toán',
  kIdentityChecked: 'Căn cước công dân',
  kCaptureDone: 'Đã chụp thành công',
  kVideoFaceTitle: 'Quay video xác thực khuôn mặt',
  kVideoSize: 'Video sẽ có độ dài 5 giây',
  kVideoDescription:
      'Vui lòng giữ gương mặt và mặt trước giấy tờ tùy thân của bạn trước máy quay',
  kVideoTitle: 'Video xác thực khuôn mặt',
  kVideoDone: 'Đã quay thành công',
  kUploading: 'Đang tải dữ liệu...',
  kPleaseWait: 'Vui lòng chờ trong giây lát.',
  kEmptyPromo: 'Chưa có ưu đãi',
  kPromoNew: 'Đổi Rewards để tận hưởng ưu đãi \n ngay hôm nay',
  kExpendable: 'Có thể dùng',
  kUseNow: 'Dùng ngay',
  kHaveUse: 'Đã dùng',
  kLetUse: 'Sử dụng ngay',
  kConfirmVideo: 'Xác nhận video',
  kPleaseConfirmVideo:
      'Vui lòng xác nhận video đã rõ nét, gương mặt và giấy tờ tùy thân có trong hình',
  kIdentityCard: 'Chứng minh nhân dân',
  kFront: 'Mặt trước',
  kPutPaperCenter: 'Vui lòng căn chỉnh giấy tờ vào giữa khung',
  kSelectTypeCard: 'Chọn loại giấy tờ',
  kCitizenIdentity: 'Căn cước công dân',
  kPassport: 'Hộ chiếu',
  kPhotoConfirm: 'Xác nhận hình chụp',
  kEnsureClearPicture:
      'Hãy đảm bảo hình chụp rõ ràng dễ đọc, \nkhông bị mờ tối hay chói sáng',
  kCapture: 'Chụp lại',
  kBackside: 'Mặt sau',
  kRedo: 'Làm lại',
  KTransfersOffChange: 'Chuyển Off-chain',
  KTransfersOnChange: 'Chuyển On-chain',
  kStatus: 'Trạng thái',
  kDoing: 'Đang thực hiện',
  kTransactionId: 'Mã giao dịch',
  kTransactionTime: 'Thời gian giao dịch',
  kReceiveAccount: 'Tài khoản nhận',
  kCompleted: 'Hoàn tất',
  kPayments: 'Hình thức',
  kSuccess: 'Thành công',
  kSendOff: 'Gửi Off-chain',
  kSendOn: 'Gửi On-chain',
  kNote: 'Lưu ý: ',
  kContentNote:
      'Chỉ gửi BTC đến địa chỉ này, việc gửi các loại \ntiền hoặc token khác đến địa chỉ này có thể khiến \nbạn mất tiền và token mà không thể khôi phục',
  kEKYC: 'eKYC',
  kNoteSendOn:
      'Để giảm thiểu rủi ro cho bạn, tính năng “Send \nOn-chain” sẽ mặc định được vô hiệu hóa',
  kNoteEKYC:
      'Bạn cần hoàn thành xác minh tài khoản \n(eKYC) trước khi sử dụng tính năng này',
  kActiveNow: 'Kích hoạt ngay',
  kVerifiNow: 'Xác minh ngay',
  kInformationReceiver: 'Thông tin người nhận',
  kHintInformationReceiver: 'Email / SĐT / Tên tài khoản',
  kNumOfBTC: 'Số lượng BTC',
  kInputNum: 'Nhập số lượng',
  kServiceCharge: 'Phí dịch vụ: ',
  kSendNow: 'Gửi ngay',
  kAddressOnChain: 'Địa chỉ ví On-chain',
  kInputAddress: 'Nhập địa chỉ',
  kTransferFree: 'Chuyển thường (miễn phí)',
  kConfirmEmail: 'Xác thực qua email',
  kOtpSendToMail: 'Nhập mã OTP đã được gửi qua email',
  kVerifyCode: 'Mã xác thực',
  kAuthenSMS: 'Xác thực qua SMS',
  kCheckSMS: 'Kiểm tra tin nhắn để nhận mã OTP',
  kCheckMail: 'Kiểm tra email để nhận mã OTP',
  kToFriend: 'Chuyển đến bạn bè',
  kFriendOfUser: ' (%s/%s đã xác thực)',
  kAll: 'Tất cả',
  kTrustPay: 'Bitback',
  kInputSearch: 'Nhập tên hoặc số điện thoại',
  kNoteUpdateVerify:
      'Để đảm bảo an toàn, vui lòng cập nhật và xác minh \ngiao dịch qua cả email và số điện thoại',
  kSendToFriend: 'Chuyển tiền đến bạn bè',
  kContactOrPhoneNumber: 'Danh bạ hoặc Số điện thoại',
  kBankAccount: 'Tài khoản ngân hàng',
  kATMOrAccountNumber: 'Thẻ ATM hoặc số tài khoản',
  kRecentTransaction: 'Giao dịch gần đây (%s)',
  kDomesticAtm: 'Thẻ ATM nội địa',
  kChange: 'Thay đổi',
  kTypeCreditNumber: 'Nhập số thẻ',
  kCreditCardExpirationDate: 'Ngày hiệu lực',
  kMessageTypeCreditNum: 'Nhập số thẻ ở mặt trước thẻ',
  kChargeMoney: 'Số tiền nạp (đ)',
  kTypeChargeMoney: 'Nhập số tiền nạp',
  kTypeChargeMoneyVnd: 'Nhập số tiền (đ)',
  kTooltipMessage: 'Nhập lời nhắn (tối đa 100 ký tự)',
  kRecommendTrustPay:
      'chưa có tài khoản Bitback. Giới thiệu ngay để được nhận những ưu đãi hấp dẫn.',
  kCancel: 'Hủy bỏ',
  kTransactionDetail: 'Chi tiết giao dịch',
  kAccountTrustPay: 'Tài khoản Bitback',
  kSenderFullName: 'Họ tên người nhận',
  kContactName: 'Tên danh bạ',
  kMethod: 'Phương thức',
  kBankTransfer: 'Chuyển khoản ngân hàng',
  kMoMoTransfer: 'Momo',
  kZaLoTransfer: 'Zalo',
  kDepositIntoTrustPay: 'Nạp tiền vào tài khoản Bitback',
  kCashBack: 'Bitback',
  kTabCashBack: 'Cashback',
  kCashBackExpect: 'Cashback (dự kiến)',
  kUnitVNDC: '%s VNDC',
  kNumCard: 'Số thẻ',
  kRemittanceCode: 'Mã chuyển tiền',
  kDepositIntoBank: 'Nạp tiền qua chuyển khoản ngân hàng',
  kDomesticCard: 'Thẻ ATM nội địa',
  kATMTransfer: 'Thanh toán thẻ ATM nội địa',
  kCreditCardTransfer: 'Thanh toán thẻ tín dụng',
  kAffiliateAccount: 'Tài khoản liên kết',
  kTransferToFriend: 'Chuyển tiền đến bạn bè',
  kTransferBank: 'Chuyển tiền qua tài khoản ngân hàng',
  kAccountNumber: 'Số tài khoản',
  kBank: 'Ngân hàng',
  kMessage: 'Lời nhắn',
  kSaveInfoForLater: 'Lưu thông tin cho lần sử dụng sau',
  kNumATM: 'Số thẻ ATM',
  kFullNameOwnerCard: 'Họ tên chủ thẻ',
  kEffectiveDate: 'Ngày hiệu lực',
  kMyCard: 'Thẻ của tôi',
  kOther: 'Khác',
  kSupport: 'Hỗ trợ',
  kConfirmDelivery: 'Xác nhận đã chuyển',
  kInfoTransfer: 'Thông tin chuyển khoản',
  kNoteTransfer:
      'Vui lòng chuyển khoản số tiền muốn nạp tới thông \ntin tài khoản bên dưới:',
  kAccountOwner: 'Chủ tài khoản',
  kBranch: 'Chi nhánh',
  kContent: 'Nội dung',
  kSystemChecking:
      'Hệ thống đang kiểm tra trạng thái \nlệnh chuyển tiền. Vui lòng chờ \ntrong giây lát...',
  kSystemCheckingFail:
      ' Hệ thống vẫn chưa ghi nhận lệnh \nchuyển tiền của bạn. Tài khoản \ncủa bạn sẽ được ghi có ngay khi \nhệ thống ghi nhận thành công',
  kTrade: 'Giao dịch',
  kChooseWithdrawal: 'Chọn nơi rút về',
  kSelectedBank: 'Chọn ngân hàng',
  kTypeAccountNumber: 'Nhập số tài khoản',
  kWithdrawalMoney: 'Số tiền rút (₫)',
  kWithdrawalIntoBank: ' Rút tiền về tài khoản ngân hàng',
  kWithdrawalIntoDomesticATM: ' Rút tiền về thẻ ATM nội địa',
  kWithdrawalIntoMyCard: ' Rút tiền về tài khoản liên kết',
  kIdentified: 'Đã định danh',
  kInfo: 'Thông tin',
  kMyProfile: 'Hồ sơ của tôi',
  kChangePassword: 'Đổi mật khẩu',
  kCardManagement: 'Quản lý thẻ',
  kFaceId: 'Face ID',
  kAllowNotify: 'Cho phép thông báo',
  kTermProfile: 'Điều khoản và điều kiện',
  kIdentifyAccount: 'Định danh tài khoản (eKYC)',
  kSecret: 'Bảo mật & Định danh',
  kLogout: 'Đăng xuất',
  kTrustPayEmptyMessage:
      'Xác minh thông tin để kích hoạt thẻ Bitback và sử dụng các dịch vụ',
  kAssociateCardEmptyMessage:
      'Liên kết tài khoản ngân hàng để có thể nạp và rút tiền nhanh chóng',
  kTrustPayCard: 'Thẻ Bitback',
  kAssociateCard: 'Thẻ liên kết',
  kCreditNumMasked: '•••• •••• •••• ••••',
  kAssociateSuccess: 'Liên kết tài khoản \n thành công',
  kCancelAssociateSuccess: 'Hủy liên kết thẻ \n thành công',
  kReceiveBankInfo: 'Thông tin ngân hàng nhận',
  kTitleInputCreditOrAccount: 'Nhập số thẻ hoặc số tài khoản',
  kHintInputCreditOrAccount: 'Số thẻ hoặc số tài khoản',
  kTypingReceiveName: 'Nhập họ tên người nhận',
  kMessageSendViaBank: 'Nhập lời nhắn (không dấu và các ký tự đặc biệt)',
  kBuyNow: 'Mua ngay',
  kPay: 'Thanh toán',
  kMax: 'Max',
  kPromotion: 'Ưu đãi',
  kContact: 'Liên hệ',
  kRefundPayment: 'Thanh toán hoàn tiền',
  kSymbol: '(%s)',
  kContentIntroduce:
      'Giới thiệu một người bạn đăng ký Bitback, bạn sẽ nhận được %s Satoshi(SAT) và người bạn giới thiệu sẽ nhận được %s Satoshi(SAT)',
  kIntroduceSat: 'Nhập mã giới thiệu để nhận %s Satoshi',
  kReferralLink: 'Đường dẫn',
  kSocialShare: 'Chia sẻ mạng xã hội',
  kReceived: 'Bạn đã nhận',
  kEmail: 'Email',
  kInputEmail: 'Email',
  kSaveInfo: 'Lưu thông tin',
  kPhotoLibrary: 'Thư viện ảnh',
  kCamera: 'Camera',
  kExit: 'Thoát',
  kOldPassword: 'Mật khẩu cũ',
  kErrorConfirmPassword: 'Xác nhận mật khẩu không chính xác',
  kNotEnoughBalance: 'Số dư của bạn không đủ để \nthực hiện giao dịch',
  kRechargeMore: 'Nạp thêm tiền',
  kCancelTransaction: 'Hủy giao dịch',
  kInputQrCode: 'Đưa mã QR vào khung',
  kPaymentCode: 'Mã thanh toán',
  kAutomaticUpdate: 'Tự động cập nhật sau %ss',
  kReNew: 'Làm mới',
  kPromoCode: 'Mã ưu đãi',
  kChooseCode: 'Chọn mã',
  kPaymentQrCodeTitle: 'Chỉ cung cấp mã thanh toán cho thu ngân',
  kFree: 'Miễn phí',
  kWithDraw: 'Withdraw',
  kWithExchange: 'Quy đổi',
  kAnnualFee: 'Phí thường niên',
  kAssociateBank: 'Ngân hàng liên kết',
  kActivationDate: 'Ngày kích hoạt',
  kAssociateDate: 'Ngày liên kết',
  kCancelAssociate: 'Hủy liên kết',
  kAssociateCardDetail: 'Chi tiết thẻ liên kết',
  kConfirmDeleteCard:
      'Bạn có chắc muốn ngừng liên kết ví Bitback với tài khoản ngân hàng?',
  kAccount: 'Tài khoản',
  kCashbackAvailable: 'Cashback khả dụng',
  kCashbackPending: 'Cashback chờ duyệt',
  kValueCashBack: '%s triệu tiền đã hoàn',
  kCategory: 'Danh mục',
  kPopular: 'Phổ biến',
  kSort: 'sắp xếp',
  kAppetizer: 'Khai vị',
  kOldCustomer: 'Khách hàng cũ',
  kNewCustomer: 'Khách hàng mới',
  kReadBeforeBuy: 'Đọc kỹ trước khi mua sắm bạn nhé!',
  kRefundWhen: 'Hoàn tiền khi nào?',
  kCashBackDetail: 'Chi tiết Cashback',
  kContentRefund:
      'Hoàn tiền được áp dụng trên số tiền cuối cùng sau khi đã trừ đi khuyến mãi, giảm giá, thuế VAT và chi phí vận chuyển.',
  kContentBill:
      'Đơn hàng sẽ được ghi nhận sau 24-48h kể từ lúc bạn đặt hàng thành công.',
  kContentTimeRefund:
      'Nhận hoàn tiền vào 60-90 ngày tiếp theo kể từ ngày đơn hàng được ghi nhận trên app Bitback.',
  kReadCarefully: 'Đọc kỹ trước khi mua sắm',
  kRefundTime: 'Thời gian hoàn tiền',
  kImportantRules: 'Quy định quan trọng cần chú ý tránh mất hoàn tiền',
  kRefundsNotAccept: 'Không chấp nhận hoàn tiền',
  kContentStore:
      'Trong một lần thanh toán đơn hàng: Nếu cùng một Shop, có thể mua nhiều sản phẩm khác nhau. Nếu khác Shop, nên tách đơn hàng hoặc mua với hình thức thanh toán trả trước.',
  kContentMoneyBag:
      'Mỗi lần thành toán chỉ được hoàn tiền tối đa 27,500 ₫, bạn nên tách đơn hàng thanh toán nhiều lần.',
  kContentPicture:
      'Không click vào Banner quảng cáo của thương hiệu sau khi chuyển từ ứng dụng Bitback qua.',
  kContentCart:
      'Không thêm sản phẩm vào GIỎ HÀNG trên website hoặc ứng dụng của thương hiệu TRƯỚC KHI Click từ Bitback qua.',
  kContentComputer:
      'Mỗi Click Mua Ngay chuyển qua ứng dụng chỉ được HOÀN THÀNH 1 LẦN THANH TOÁN. Mở lại ứng dụng Bitback để mua đơn hàng mới.',
  kContentIncorrect1:
      'Các trường hợp tự tạo shop mua hàng, mua đi bán lại số lượng lớn sẽ không được hoàn tiền hoặc bị khóa tài khoản.',
  kContentIncorrect2:
      'Chỉ áp dụng hoàn tiền khi mua hàng qua ỨNG DỤNG. Hãy cài đặt ứng dụng trước khi mua.',
  kContentIncorrect3:
      'Hủy đơn, đổi trả, bom hàng hoặc tự tạo Shop và mua hàng để nhận hoa hồng',
  kPizzaVoucher: 'Ưu đãi The Pizza Company',
  kNotAddProductBefore: 'Không thêm sản phẩm vào giỏ hàng từ trước',
  kNotPayMultipleOrders: 'Không thanh toán nhiều đơn hàng liên tiếp',
  kContentNotAddProductBefore:
      'Nếu bạn đã thêm sản phẩm vào giỏ hàng \ntrước khi chuyển từ Bitback qua đối tác, \nviệc hoàn tiền sẽ không được áp dụng.',
  kContentNotPayMultipleOrders:
      'Mỗi Click MUA NGAY chỉ ghi nhận hoàn tiền \ncho MỘT lần thanh toán. Quay lại Bitback \nnếu bạn muốn mua tiếp.',
  kOkCreateCart: 'OK, Tạo giỏ hàng mới',
  kOKSlowlyButSurely: 'OK, Chậm mà chắc',
  kSelectCategory: 'Chọn danh mục',
  kA2Z: 'Tên A-Z',
  kZ2A: 'Tên Z-A',
  kHighCashBack: 'Cashback cao',
  kSearch: 'Tìm kiếm',
  kSearchNear: 'Tìm kiếm gần đây',
  kClose: 'Đóng',
  kCancelOrder: 'Cancel',
  kCancelSellEgg: 'Cancel',
  kNotFound: 'Không có kết quả phù hợp',
  kCheckSearch: 'Vui lòng kiểm tra chính tả\nhoặc sử dụng các gợi ý',
  kSummary: 'Total value',
  kRewardPending: 'Thưởng chờ duyệt',
  kOpenVNDC: 'Bạn chưa có ví nhận Bitcoin?',
  kOpenBitCoin: 'Mở tài khoản ONUS\nđể nhận ngay 200,000 VNDC',
  kGeneralRules: 'Quy định chung',
  kTimeRefund: 'Thời gian hoàn tiền',
  kRefund_1: 'Hoàn tiền được áp dụng trên số tiền cuối cùng sau khi đã',
  kRefund_2: ' trừ đi khuyến mãi, giảm giá, thuế VAT và chi phí vận chuyển.',
  kRefund_3: 'Đơn hàng sẽ được ghi nhận sau',
  kRefund_4: ' 24-48h ',
  kRefund_5: 'kể từ lúc bạn đặt hàng thành công.',
  kRefund_6: 'Nhận hoàn tiền vào',
  kRefund_7: ' 60-90 ngày tiếp theo',
  kRefund_8: ' kể từ ngày đơn hàng được ghi nhận trên app Bitback.',
  kRefund_9:
      'Trong một lần thanh toán đơn hàng: Nếu cùng một Shop, có thể mua nhiều sản phẩm khác nhau. ',
  kRefund_10:
      'Nếu khác Shop, nên tách đơn hàng hoặc mua với hình thức thanh toán trả trước.',
  kRefund_11: 'Mỗi lần thành toán chỉ được hoàn tiền tối đa ',
  kRefund_12: '27,500 ₫,',
  kRefund_13: ' bạn nên tách đơn hàng thanh toán nhiều lần.',
  kRefund_14: 'Không click vào Banner quảng cáo của thương hiệu ',
  kRefund_15: 'sau khi chuyển từ ứng dụng Bitback qua.',
  kRefund_16: 'Không thêm sản phẩm vào GIỎ HÀNG ',
  kRefund_17: 'trên website hoặc ứng dụng của thương hiệu ',
  kRefund_18: 'TRƯỚC KHI Click từ Bitback qua.',
  kRefund_19: 'Mỗi Click Mua Ngay ',
  kRefund_20: 'chuyển qua ứng dụng chỉ được ',
  kRefund_21: 'HOÀN THÀNH 1 LẦN THANH TOÁN. ',
  kRefund_22: 'Mở lại ứng dụng Bitback để mua đơn hàng mới.',
  kImportants: 'Quy định quan trọng cần chú ý tránh mất hoàn tiền',
  kNotRefund: 'Không chấp nhận hoàn tiền',
  kCountDown: 'Bảng xếp hạng',
  kRewardMe: 'Ưu đãi của tôi',
  kWantBTC: 'Số Satoshi muốn rút',
  kWantTransfer: 'Số lượng %s muốn rút',
  kWantBBC: 'Số lượng BBC muốn rút',
  kEmailOrPhone: 'Nhập email hoặc sđt',
  kHasAmount: 'Bạn đang có',
  kRewardMin: 'Số tối thiểu trên một giao dịch là %s',
  kLimitReward: 'Hạn mức trong ngày là %s',
  kEmailTransfer: 'Email hoặc SĐT đăng nhập ví %s',
  kFeeTransfer: 'Phí giao dịch: %s',
  kTotalTransfer: 'Tổng số lượng(đã báo gồm phí giao dịch)',
  kAddressKai: 'Địa chỉ ví',
  kCheckVNDC: 'Kiểm tra ví VNDC',
  kCampaign: 'Chiến dịch',
  kWhatBlockChain: 'Công nghệ Blockchain là gì?',
  kTPP: '%s TPP',
  kDoMission: 'Làm nhiệm vụ',
  kErrorOtp: 'Mã OTP không chính xác, hãy thử lại',
  kMinimumToRedeem: 'Số tối thiểu để đổi thưởng là 20,000 Sat',
  kSpin: 'Vòng quay',
  kGameChicken: 'BitFarm',
  kDescriptionPending: 'Tài khoản của bạn đang chờ xác thực\nCảm ơn!',
  kDescriptionAccept: 'Tài khoản của bạn đã được xác thực\nCảm ơn!',
  kDescriptionReject: 'Xác thực không thành công\nVui lòng thử lại',
  kNotData: 'Không có dữ liệu',
  kDashboard: 'Dashboard',
  kSum: 'Tổng',
  kPaid: 'Đã thanh toán',
  kRosesThisMonth: 'Hoa hồng tháng này',
  kBonus: 'Thưởng',
  kGD: 'GD',
  kTransactionHistory: 'Lịch sử giao dịch',
  kApproved: 'Đã duyệt',
  kCheckingProgress: 'Đang đối soát',
  kPoundage: 'Tiền Hoa hồng',
  kDepositSat: 'Số SAT muốn nạp',
  kTitleDeposit: 'Deposit',
  kDetailDeposit: 'Chi tiết nạp',
  kMain: 'Trang chủ',
  kFarm: 'Trang trại',
  kChickenMarket: 'Chợ gà',
  kHistoryFarm: 'Giao dịch',
  kLevelFarm: 'Xếp hạng',
  kOtherFarm: 'Thêm',
  kCollect: 'Bộ sưu tập',
  kNewEvent: 'Sự kiện',
  kError: 'Có lỗi xảy ra vui lòng thử lại.',
  kEggHatch: 'Trứng sắp nở rồi!',
  kFriend: 'Bạn bè',
  kCodeIntroduce: 'Mã giới thiệu',
  kGiftFriend: 'Phần thưởng giới thiệu bạn bè',
  kTime: 'Thời gian',
  kFriendKyc: 'Bạn bè đã KYC',
  kMember: 'Thành viên',
  kRank: 'Hạng',
  kUnregisteredKyc: 'Chưa KYC',
  kRegisteredKyc: 'Đã KYC',
  kOpenBitback: 'Giới thiệu bạn bè',
  kGetNow: 'nhận ngay',
  kCopied: 'Copied',
  kCodeIntroduceNotFound: 'Không tìm thấy mã giới thiệu',
  kNewUpdate: 'Bản cập nhật mới đã sẵn sàng!',
  kUpdateNow: 'Cập nhật ngay',
  kComeBackLate: 'Hãy trở lại sau nhé!',
  kSystemUpgrades:
      'Chúng tôi xin lỗi cho sự bất tiện này. Chúng tôi đang nâng cấp hệ thống để giúp trải nghiệm được tốt hơn.',
  kIncorrectSatoshi: 'SAT bạn nhập không chính xác',
  kCheckSatoshi: 'Kiểm tra lại số Satoshi',
  kCashbackAvailableInvalid: 'Bạn không đủ số Sat để mua',
  kInvalidCredentials: 'Mật khẩu bạn nhập không chính xác',
  kPhoneExist: 'Số điện thoại đã được sử dụng ở tài khoản khác',
  kEggInvalid: 'Trứng không hợp lệ',
  kBadRequest: 'Máy chủ đang bận, vui lòng thử lại sau',
  kAccountTemporarilyLocked: 'Tài khoản của bạn đã bị khoá.',
  kUnauthorized: 'Phiên đăng nhập đã hết hạn',
  kCheckPhoneNumber: 'Kiểm tra lại số điện thoại',
  kPhoneEmpty: 'Số điện thoại không để trống.',
  kLoginGoogle: 'Đăng nhập qua Google',
  kLoginFacebook: 'Đăng nhập qua Facebook',
  kCheckCodeIntroduce: 'Kiểm tra lại mã giới thiệu',
  kCheckEmail: 'Kiểm tra lại email',
  kInputAmount: 'Nhập số lượng để đổi thưởng',
  kValidSat: 'Satoshi không chính xác',
  kHoldMin: 'Duy trì số dư tối thiểu: %s',
  kValidAmount: 'Số %s bạn đổi không khả dụng',
  kTransferUnLimit: 'Giao dịch không vượt quá %s',
  kValidAcount: 'Tài khoản ví %s không hợp lệ.\n Vui lòng kiểm tra lại',
  kValidEmail: 'Email không đúng định dạng',
  kCheckInfo: 'Kiểm tra lại thông tin',
  kAccountInvalid: 'Tài khoản không chính xác',
  kInvalidBalance: 'Giao dịch thất bại, vui lòng thử lại sau',
  kAmountInvalidMin: 'Giao dịch quá nhỏ',
  kAmountInvalidMax: 'Giao dịch không vượt quá %s',
  kAmountInvalidDay: 'Hạn mức giao dịch trong ngày là %s',
  kAmountInvalid: 'Invalid transaction',
  kAccountTransferInvalid: 'Tài khoản không chính xác',
  kHandleInvalid: 'Giao dịch xử lý lỗi',
  kAmountInvalidMonth: 'Giao dịch vượt quá hạn mức trong tháng',
  kHasTransactionPending: 'Đã có giao dịch đang chờ xử lý',
  kTutorialStep: 'Hướng dẫn bạn bè 3 bước nhận thưởng',
  kTutorialStep1: 'Mời bạn bè tải ứng dụng Bitback theo đường dẫn bên dưới',
  kTutorialStep2: 'Đăng ký với mã giới thiệu',
  kTutorialStep3: 'Định danh (KYC) và Nhận thưởng',
  kDataNotFound: 'Dữ liệu trống',
  kSomeWentWrong: 'Có lỗi xảy ra. Vui lòng thử lại sau hoặc liên hệ hỗ trợ.',
  kTooManyRequest: 'Too many requests',
  kBodyRequire: 'Thiếu thông tin',
  kPhoneInvalid: 'Số điện thoại không đúng',
  kPhoneExists: 'has already been taken',
  kTitlePhoneExists: 'This phone number',
  kTypeRequire: 'Chưa chọn loại tài khoản',
  kEmailExists: 'Email đã được sử dụng',
  kPassCodeInvalid: 'Mật mã không đúng',
  kFullNameRequire: 'Chưa nhập họ tên',
  kTokenInvalid: 'Login session is incorrect',
  kOtpInvalid: 'Mã xác thực không đúng',
  kEmailInvalid: 'Email đã được sử dụng',
  kCashBackAvailable: 'kCashBackAvailable',
  kAccountLocked: 'Tài khoản của bạn đã bị khoá.',
  kUnAuthorized: 'Phiên đăng nhập hết hạn. Vui lòng đăng nhập lại.',
  kTransactionPending: 'Bạn có 1 giao dịch đang chờ xử lý',
  kTitleExchange: 'Quy đổi tài sản',
  kRatioExchange: 'Tỉ lệ quy đổi: 1 %s ~ %s %s',
  kExchangeTo: 'Sang',
  kExchangeFrom: 'Quy đổi từ',
  kSelectedExchange: 'Chọn tài sản quy đổi',
  kAmountExchange: 'Nhập số lượng %s quy đổi',
  kMinAmountExchange: 'Số lượng quy đổi tối thiểu: %s',
  kValidAmountExchange: 'Số %s quy đổi không khả dụng',
  kValidInputAmount: 'Số %s bạn nhập không chính xác',
  kButtonExchange: 'Quy đổi trong (%ss)',
  kUpdatePriceExchange: 'Cập nhật giá',
  kEarnSat: 'Earn Satoshi',
  kTimeRemaining: 'Thời gian còn lại',
  kHasSatoshi: 'Số satoshi đang có',
  kSatReceiver: 'Số satoshi trả thưởng',
  kProgramEnd: 'Chương trình đã kết thúc',
  kLastGame: 'Đã diễn ra(%s)',
  kGoingGame: 'Đang diễn ra(%s)',
  kInformation: 'Information',
  kUserInformation: 'Information',
  kPrizes: 'Giải thưởng',
  kRemaining: 'Còn lại ',
  kEndGame: 'Đã kết thúc',
  kPlayFree: 'CHƠI MIỄN PHÍ',
  kPlayNow: 'CHƠI NGAY',
  kFeePlayGame: 'Phí %s',
  kRanking: 'Hạng',
  kPlayer: 'Người chơi',
  kScore: 'Điểm',
  kFriends: 'Danh sách bạn bè',
  kFacebook: '\t Facebook',
  kZalo: '\t Zalo',
  kTelegram: '\t Telegram',
  kWheelDaily: 'VÒNG QUAY HÀNG NGÀY',
  kWheel: 'QUAY, QUAY, QUAY',
  kReceiverReward: 'get rewarded\t',
  kTitleWheel:
      'Mỗi ngày khi đăng nhập vào ứng dụng \nbạn sẽ nhận được một lượt quay \nđể nhận thưởng ',
  kTitle2Wheel: 'will get a spin to',
  kHasWheel: 'You have 1 spin left',
  kEndWheel: 'You run out of spins',
  kWheelNow: 'Spin now',
  kSelectCashBack: 'Select the asset you want to withdraw',
  kDraw: 'Withdraw',
  kTopBalance: 'Balance %s',
  kButtonActivated: 'Activated',
  kAccountUnActivated: 'Your account has not been activated',
  kAccountRejected: 'Your account has been denied',
  kConfirmAgain: 'Re-Authentication',
  kAccountPending: 'Your account is being processed',
  kAccountIdentifier: 'Your account has not been identified',
  kIdentifier: 'Identification',
  kHarvest: 'Harvest',
  kHarvestEggBreed: 'Harvesting hatching eggs',
  kBreed: 'Insemination',
  kBuyEgg: 'Buy egg',
  kBuyChicken: 'Buy chicken',
  kEmptyRooster: 'Let\'s buy some roosters!',
  kEmptyBreed: 'There are no pairs of chickens\n breeding',
  kEmptyEgg: 'Buy some eggs\n to hatch or breed!',
  kEmptyChicken: 'Let\'s buy some chickens!',
  kBreeding: 'Mixing',
  kSelling: 'On sale',
  kForSell: 'For sale',
  kOpenEgg: 'Open eggs',
  kPriceBBC: ' %s BBC',
  kTitleSellOk: 'Successfully sold',
  kTitleSellChicken: 'Chicken market with price',
  kMgsChicken: 'Chicken %s on the chicken market for the price',
  kYouReceiver: 'Congratulation! You receive',
  kFeeBBC: 'Fee ~ %s BBC',
  kFeeRatio: 'Fee ~ %s%',
  kDetailChicken: 'Specificity',
  kChicken: 'Chicken %s',
  kIdChicken: 'ID Gà',
  kTitleLevel: 'Level',
  kValueLevel: 'Level %s',
  kProductivityDaily: 'Productivity per day',
  kRate: 'Expected interest rate',
  kTimeLevel: 'Level up time',
  kValueTimeLevel: '%s Day',
  kLongevity: 'Longevity',
  kRemainingBreed: 'Số lần phối giống còn lại',
  kBuy: 'Purchase',
  kMaxLevel: 'You are already at the highest level',
  kPrepareUpLevel: 'Prepare to level up %s',
  kRemainingLevel: '%s days left to level up %s',
  kProductNotExists: 'The product you purchased no longer exists',
  kConfirmBuyChicken: 'Confirmation of payment for chicken',
  kConfirmBuyEgg: 'Confirmation buying eggs',
  kTransactionSuccess: 'Successful transaction',
  kSell: 'Sell',
  kSellEgg: 'Eggs for sale',
  kSetPrice: 'Set price',
  kSellYellowEgg: 'Selling golden eggs',
  kAmount: 'Amount',
  kInputEgg: 'Enter the number of eggs',
  kTurnover: 'Revenue',
  kLabelNote: 'Note: ',
  kTitlePass: 'Password is incorrect',
  kInputAgain: 'Please try again.',
  kSelectToken: 'Bấm vào để lựa chọn',
  kMaxSellEgg: 'Exceeded the maximum number of eggs',
  kAmountEgg: 'Amount must be a multiple of %s',
  kRankFarm: 'Farm Ranking',
  kOwnerFarm: 'Farm owner',
  kQuantityChicken: 'Number of chickens',
  kQuantityEgg: 'Number of eggs',
  kQuantityYellowEgg: 'Number of golden eggs',
  kTypeTransaction: 'Transaction type',
  kDone: 'Done',
  kForSellChicken: 'Chicken for sale',
  kProduct: 'Product',
  kInvalidPrice: 'Check the selling price',
  kPrice: 'The selling price must be a multiple of 100',
  kMinPrice: 'Selling price should not be less than 1000 Sat',
  kMaxPrice: 'Selling price does not exceed 1,000,000 Sat',
  kFeeBreed: 'Breeding costs',
  kTimeBreed: 'Mating time',
  kStartBreed: 'Start mating',
  kSelectRooster: 'Choose a rooster',
  kSelectChicken: 'Choose a hen',
  kEmptySlot: 'Your farm lacks %s space to open hatching eggs',
  kChooseChicken: 'Choose a pair of chickens to breed',
  kChoose: 'Select',
  kChooseAgain: 'Reselect',
  kFeeBreeding: 'Cost',
  kConfirmBreeding: 'Confirmation of mating',
  kTitleBreed:
      'The pair of chickens you choose to breed is not of the same type. Please choose again!',
  kPriceSell: 'Price',
  kSellOne: 'Each time you buy %s eggs',
  kBuyChickenOnMarket: 'Buy on market',
  kBuyFromBitBack: 'Buy from Bitfarm',
  kChooseBuyEgg: 'Choose where to buy eggs',
  kEggBreed: 'Hatching eggs',
  kInputBBC: 'Enter SAT number',
  kAgreeSell: 'Agree to sell',
  kConfirmBuy: 'Confirmation',
  kSellPlaceChicken: 'You want to buy more chicken space?',
  kThank: 'Thank you!',
  kTransactionLater: 'Let\'s do it again in a few minutes',
  kTransactionFail: 'Transaction failed',
  kHasPlaceChicken: 'You\'ve got 1 more place to raise chickens',
  kBuySlot: 'Buy more seats',
  kFullSlot: 'Sorry! Your farm\n is currently out of space.',
  kBuyEggPending: 'Purchase order is pending.\nThanks!',
  kHasAccountYet: 'Do you already have a %s account?',
  kTransferBitBack: 'To withdraw assets from Bitback',
  kNeedAccount: 'you need an account %s',
  kHasAccount: 'I have an account %s',
  kNoHasAccount: 'I don\'t have an account %s',
  kWalletPayme: 'Payme Wallet',
  kMinAmountPayme: 'Satoshi number is not less than 10,000',
  kMaxAmountPayme: 'Satoshi number does not exceed 1,000,000',
  kPendingTransactionPayme: 'You have a pending transaction.',
  kConfirmNotTransaction: 'Confirm you haven\'t paid',
  kCancelTransactionPayme: 'Confirm you haven\'t paid',
  kTransactionPayme: 'If already paid, please',
  kAwaitSystemPayme: 'Wait for the system to confirm.',
  kAwaitPayme: 'Keep waiting',
  kCancelPayme: 'Cancellation confirmation',
  kQuantityInvalid: 'An error occurred, please try again later.',
  kPriceSellEgg: '%s egg = ',
  kBuyEggLater: 'It\'s not yet time to buy Rooster Eggs',
  kBuyEggRoosterLater: 'It\'s not yet time to buy Eggs',
  kPleaseBackCome: 'Please come back later.',
  kMessageBuyEggLater: 'Come back later',
  kTimeOpenEgg: 'It\'s time to open the egg',
  kOpen: 'Open',
  kFeatureUpdate: 'Feature is being updated',
  kNotEnoughSat: 'You don\'t have enough satoshi to buy.',
  kNotEnoughBBC: 'Bạn không đủ BBC để mua.',
  kAddSat: 'Please refill!',
  kAwaitOpenEgg:
      'Don\'t sell eggs in a hurry\n Please wait patiently for the eggs to hatch',
  kCongHarvest: 'Congratulations on your harvest',
  kNumberEgg: '+%s Gold egg',
  kBuyYellowEggBitback: 'Successfully sold eggs for Bitback',
  kPleaseLater: 'Please come back in',
  kTransactionFailPurchase:
      'Transaction failed!\nPlease try again in a few minutes\nThanks!',
  kPendingTransactionPurchase: 'Transaction in progress\nPlease wait a moment!',
  kLoginWith: 'Login with',
  kSkipLogin: 'Skip',
  kExitAccount: 'Sign out',
  kSignIn: 'Sign In',
  kPaymentPayme: 'Cổng thanh toán Payme',
  kFaceIdUnActivated: 'Face ID is not available',
  kTouchIdUnActivated: 'Touch ID is not available',
  kLaterSetting: 'Activate after in setting.',
  kEnableTouchId: 'Enable Touch ID/Face ID',
  kDisableTouchId: 'Disable Touch ID/Face ID',
  kCheckPassCode: 'Check your password',
  kSelectBiometric: 'Choose a form of authentication',
  kTotalEgg: 'Total: %s',
  kQuestion: 'Giải trí & Nhiệm vụ nhận thưởng',
  kLikeGame: 'Trò chơi được yêu thích',
  kTimeGame: 'Còn lại',
  kUserGame: 'Người chơi',
  kRewardGame: 'Phần thưởng',
  kDescriptionCampaign: 'Mở tài khoản ngân hàng',
  kTabbarGame: 'Games',
  kTabbarwallet: 'Wallet',
  kTabbarLaunchpad: 'Launchpad',
  kFirstMission: 'The first mission',
  kDescriptionMission:
      'Verify your phone number, to get reward %s SAT and experience all Bitback App features.',
  kDeviceUnSupport: 'Device not support this feature',
  kSelectMethod: 'Select an entry method',
  kUnlimitedPlay: '  Unlimited pass',
  kLimitedPlay: '1-time pass',
  kAvailableBBC: 'Available BBC: %s',
  kPayBBC: 'Pay with BBC',
  kNext: 'Next',
  kInvalidOtp: 'The verification code is incorrect',
  kExpiresOtp: 'The verification code has expired',
  kTryAgainOtp: 'Please resend the verification code',
  kTryAgain2: 'to try again.',
  kTitleReferralReward: 'Referral Code Rewards',
  kInputReferralReward: 'Referral code | Email | Phone number.',
  kReceiverReferralReward: 'Enter Referral code | Email | Phone number',
  kGetReferralReward: 'to get reward ',
  kOtpVerification: 'OTP Verification',
  kEnterOtp: 'Please enter the 4-digit verification code',
  kOtpSentEmail: 'sent to email',
  kInvalidPass: 'Password doesn\'t match',
  kInvalidNumberPass: 'Password must be 6 number',
  kCreateAccountSuccess: 'Account successfully created',
  kWellComeMember: 'Welcome new member',
  kInputPassAgain: 'Confirm password',
  kInputReferralAgain: 'is incorrect, please try again.',
  kContentOtpPhone: 'Please enter the 6-digit verification code',
  kContent2OtpPhone: 'sent to phone number %s',
  kInvalidOtpPhone: 'Verification code is incorrect',
  kTitleVerifyOtp: 'OTP verification code',
  kInvalidPhone: 'The phone number does not exist',
  kManyRequestOtp: 'Bạn đã gửi yêu cầu quá nhiều lần\n\nVui lòng thử lại sau.',
  kDescriptionVerify: 'and experience all Bitback App features.',
  kTitleVerifyPhone: 'Please, verify your phone number ',
  kVerifyPhoneReward: 'to get reward',
  kVerifyPhoneFail: 'Xác thực số điện thoại thất bại',
  kTryAgain: 'Please try again.',
  kBuyHatchingEgg: 'Buy hatching egg',
  kMyWallet: 'Wallet',
  kInWallet: 'Assets',
  kPendingWallet: 'Pending',
  kAmountDeposit: 'Deposit amount',
  kMinDeposit: 'Minimun amount: %s',
  kMaxDeposit: 'Maximum amount: %s',
  kMinTradeDeposit: 'Minimun amount in a transaction: %s',
  kPayDeposit: 'Amount to be paid',
  kMethodPay: 'Payment method',
  kPendingPayment: 'You have 1 pending transaction',
  kMoreDetail: 'Details',
  kMyPerson: 'Hồ sơ của tôi',
  kIntroFriend: 'Giới thiệu bạn bè',
  kStatistical: 'Thống kê',
  kVerifyPhone: 'Xác thực số điện thoại',
  kChangePass: 'Đổi mật khẩu',
  kEnableNoti: 'Cho phép thông báo',
  kLanguage: 'Ngôn ngữ',
  kWantWithdraw: 'Withdraw amount',
  kMoneyWithdraw: 'Available balance: %s',
  kTodayWithdraw: 'Daily limit remaining: %s',
  kLocalWithdraw: 'Select place to receive',
  kTermAndPolicy: 'Điều khoản và chính sách',
  kCommunityBitback: 'Cộng đồng Bitback',
  kTouchIdFaceId: 'Touch ID/Face ID',
  kNowPass: 'Mật khẩu hiện tại',
  kConfirmNewPass: 'Xác nhận mật khẩu mới',
  kTtInvalidChangePass: 'Mật khẩu xác nhận không trùng khớp',
  kChangePassOK: 'Mật khẩu của bạn\nđã được thay đổi thành công.',
  kAccountLock: 'Tài khoản hiện đã bị khoá',
  kTabBarIntro: 'Referral',
  kGiftBag: 'Gift Bag',
  kTabbarHistory: 'History',
  kNoRank: 'Không xếp hạng',
  kTitleExpired: 'Phiên đăng ký hết hạn',
  kMgsExpired: 'Vui lòng thực hiện lại.',
  kSelectSwapCoin: 'Chọn loại tài sản muốn quy đổi',
  kSwapCoin: 'Bạn có chắc chắn muốn quy đổi\n %s sang %s?',
  kCancelSwap: 'Hủy',
  kConfirmSwap: 'Xác nhận quy đổi',
  kSuccessSwap: 'Quy đổi thành công',
  kConfirmWait: 'Tiếp tục đợi',
  kConfirmCancel: 'Bạn muốn hủy giao dịch?',
  kDesCancel:
      'Nếu bạn đã thanh toán,\nvui lòng đợi hệ thống xác nhận.',
  kTitleCancelDeposit: 'Bạn muốn hủy giao dịch?',
  kPaidDeposit: 'Nếu bạn đã thanh toán',
  kWaitConfirmDeposit: 'vui lòng đợi hệ thống xác nhận.',
  kContinueWait: 'Tiếp tục đợi',
  kPendingDeposit: 'Giao dịch đang được xử lý...',
  kOnusInfo: 'Phone number or Email registered ONUS App',
  kOnusNotFound: 'Your Onus account doesn’t exists',
  kExceededAvailableBalance: 'The amount exceeded the available balance.',
  kFeeTransaction: 'Phí giao dịch: %s',
  kInvalidAccount: 'Tài khoản không tồn tại',
  kSwapContentSuccess: 'Bạn nhận được',
  kSwapDetailWallet: 'Xem chi tiết ví',
  kSwapPending: 'Tính năng đang tạm khoá/nVui lòng thử lại sau.',
  kPending10s: 'Thực hiện quy đổi sau %s giây\nVui lòng thử lại.',
  kMinHoldExChange: 'Duy trì số dư tối thiểu: %s',
  kAvailableCoin: 'Số dư khả dụng: %s',
  kMaxExChange: 'Số lượng quy đổi tối đa: %s',
  kSessionGameEnd: 'Phiên giao dịch của bạn đã kết thúc.',
  kEmptyBBC:
      'Bạn không đủ số dư BBC. Vui lòng nạp thêm BBC vào ví trước khi chơi game.',
  kAddSlotSpiner: 'Nhận thêm lượt quay',
  kSatoshi: 'Satoshi',
  kResultSpiner: 'Chúc mừng bạn nhận được',
  kNoHappy: 'Chúc bạn may mắn lần sau',
  kRewardNext: 'Phần Thưởng %s% cho đơn hàng tiếp theo',
  kSatoshiMining: 'Satoshi Mining',
  kEndSatoshi: 'Hết Satoshi để đào',
  kEndEarnSatoshi: 'Hết lượt đào trong ngày',
  kMaintanceFeature: 'Tính năng đang bảo trì',
  kRemoveAccount: 'Xác nhận xóa tài khoản',
  kInfoRemoveAccount:
      'Tài khoản của bạn sẽ bị khóa sau 30 ngày kể từ hôm nay, Đăng nhập lại sẽ hủy quá trình này',
};
