import 'package:bitnan/@share/constants/language.constant.dart';

const Map<String, String> vi_VN = {
  KAppName: 'Bitback',
  KSelectFund: 'Chọn nguồn tiền',
  KSelectFundMoney: 'Nguồn tiền',
  KRewardWallet: 'Ví Reward',
  KTrustPayWallet: 'Ví Bitback',
  KChargeMore: ' thêm',
  KAddAssociate: 'Thêm liên kết',
  KDigitalWallet: 'Ví điện tử',
  KSurplus: 'Số dư',
  kLoading: 'Đang xử lý...',
  kHome: 'Trang chủ',
  kPlay: 'Play',
  kHistory: 'Lịch sử',
  kHistoryOnChain: 'On-Chain',
  kHistoryOffChain: 'Off-Chain',
  kHistoryPayment: 'Thanh toán',
  kHistoryReferFrom: 'Giới thiệu từ',
  kHistoryReferBy: 'Giới thiệu bới',
  kHistoryKYC: 'KYC',
  kAbout: 'Giới thiệu',
  kPerson: 'Quản lý tài khoản',
  kHello: 'Chào %s!',
  kPreMoney: '≈',
  kBTCFormat: '%s BTC',
  kSATFormat: '%s SAT',
  kMessageSuccess: 'Giao dịch của bạn đang được xử lý',
  kVNDC: 'VNDC',
  kVND: 'VND',
  kMoneyFormat: '%s VNDC',
  kConfirmation: 'Xác nhận giao dịch',
  kPromotionBuy: 'Mua ưu đãi',
  kFunds: 'Nguồn tiền',
  kInitialMoney: 'Số tiền ban đầu',
  kTransactionFee: 'Phí giao dịch',
  kDiscount: 'Giảm giá',
  kPayment: 'Số tiền thanh toán',
  kNeedPayment: 'Số tiền cần thanh toán tạm tính',
  kExchange: 'Quy đổi',
  kConfirm: 'Xác nhận',
  kActivated: 'Xác thực',
  kAccountActivated: 'Chưa kích hoạt',
  kAccountIdentification: 'Chưa định danh',
  kAccountReview: 'Chờ duyệt',
  kAccountReject: 'Yêu cầu định danh bị từ chối',
  kAccountLock: 'Tài khoản hiện đã bị khoá',
  kErrorPaynme: 'Có lỗi xảy ra.',
  kTextInputPhone: 'Nhập số điện thoại của bạn',
  kInputPhone: 'Nhập số điện thoại',
  kUpdateProfile: 'Cập nhật thành công.',
  kValidateWallet: 'Chỉ nhận địa chỉ ví BEP20',
  kPhoneNumber: 'Số điện thoại',
  kEditEmail: 'Cập nhật email',
  kVerifyEmail: 'Xác thực email',
  kChangeEmail: 'Cập nhật email',
  kContinue: 'Tiếp tục',
  kAllStores: 'Tất cả cửa hàng',
  kDirect: 'Chỉ đường',
  kDistanceFormat: '%s km',
  kGoHome: 'Về trang chủ',
  kLetPromotion: 'Xem ưu đãi',
  kMessageSuccessStart: 'Bạn Vừa dùng ',
  kMessageSuccessEnd: ' để mua voucher ưu ',
  kVoucherSuccess: 'Mua ưu đãi thành công',
  kConfirmPhone: 'Xác thực số điện thoại',
  kInputOtp: 'Nhập mã OTP đã được gửi qua số điện thoại',
  kResendOtp: 'Gửi lại mã xác thực',
  kResendOtpWithNum: 'Gửi lại mã xác thực (%s)',
  kReceiverSat: 'Nhận Satoshi',
  kChangePhoneNumber: 'Đổi số điện thoại',
  kLoginInfo: 'Thông tin đăng nhập',
  kFullName: 'Họ và tên',
  kSignUp: 'Đăng ký',
  kChangePassSuccess: 'Mật khẩu thay đổi thành công',
  kGiveCoinSuccess: 'Chúc mừng bạn đã nhận được',
  kSignUpSuccess: 'Đăng ký tài khoản \nthành công',
  kSendInfoSuccess: 'Gửi thông tin thành công',
  kIntoHome: 'Vào trang chủ',
  kUnderstood: 'Đã hiểu',
  kWatchDetail: 'Xem chi tiết',
  kAgree: 'Đồng ý',
  kMessageSendInfoSuccess:
      'Hệ thống Bitback đang xác thực \nthông tin định danh của bạn.',
  kMessageChangePassSuccess:
      'Hãy thay đổi mật khẩu thường xuyên để \ntăng tính bảo mật cho tài khoản',
  kReward: 'Phần Thưởng',
  kBalance: 'Số Dư',
  kEarnSAT: 'Đào Satoshi',
  kOfferChanged: 'Ưu đãi',
  kTransfer: 'Đổi thưởng',
  kTransferMinAmount: 'Tối thiểu: ',
  kTransferMaxAmount: 'Tối đa: ',
  kTransferTransactionFee: 'Phí giao dịch: ',
  kAvailableBalances: 'Số dư khả dụng',
  kRecharge: 'Nạp',
  kWithdrawal: 'Rút',
  kTransfersMoney: 'Quy đổi',
  kQRCode: 'Mã QR',
  kVerifyDescription:
      'Xác minh thông tin và liên kết tài khoản ngân hàng để bảo mật và thực hiện giao dịch',
  kVerifyTitle: 'Xác thực thông tin cá nhân',
  kVerifyBank: 'Liên kết ngân hàng',
  kVerifyNow: 'Xác thực ngay',
  kHotVoucher: 'Ưu đãi bán chạy',
  kMore: 'Xem thêm',
  kPriceSale: '-%s%',
  kOutstandingBrand: 'Mua sắm',
  kHotNews: 'Bản tin nóng hổi',
  kServices: 'Dịch vụ',
  kHide: 'Ẩn bớt',
  kCurrentDeal: 'Ưu đãi đang diễn ra',
  kSeeAll: 'Xem tất cả',
  kHasSat: 'Bạn đang có',
  kContactInfo: 'Thông tin liên hệ',
  kStore: 'Cửa hàng',
  kUseFaceID: 'Sử dụng Face ID',
  kLater: 'Để sau',
  kUseFaceIDAnotherTime:
      'Đăng ký sử dụng Face ID \ncho lần đăng nhập tiếp theo',
  kSeeAllAddress: 'Xem tất cả địa điểm (%s)',
  kCreatePass: 'Tạo mật khẩu',
  kNewPass: 'Mật khẩu mới',
  kConfirmPass: 'Xác nhận mật khẩu',
  kTypePassword: 'Nhập mật khẩu',
  kFaceAuth: 'Xác thực gương mặt',
  kNotify: 'Thông báo',
  kNotifyEmpty: 'Không có thông báo',
  kNotifyNew: 'Khi có tin mới, chúng tôi sẽ\nthông báo đến bạn ngay',
  kEkycIdentifier: 'Định danh eKYC',
  kTransferCoin: 'Chuyển Coins',
  kTransfersOffline: 'Thanh toán tại điểm thanh toán',
  kBarcodeTitle: 'Cung cấp mã này cho thu ngân khi thanh toán',
  kExpiration: 'Hiệu lực đến hết %s - ',
  kExpired: 'Hết hạn',
  kTitlePromotion: 'Bạn sẽ nhận được',
  kTerm: 'Điều kiện & Điều khoản',
  kLocateUse: 'Địa điểm áp dụng',
  kHelloDot: 'Xin chào, %s!',
  kInputPass: 'Mật khẩu',
  kForgetPass: 'Quên mật khẩu?',
  kWithDrawTitle: 'Giao dịch đang được xử lý',
  kWithDrawMgs: 'VNDC sẽ được chuyển vào ví ONUS.',
  kWithDrawFail: 'Rất tiếc, giao dịch thất bại',
  kTryAgainWithDraw: 'Hãy thử lại sau nhé',
  kNotMe: 'Không phải tôi',
  kVoucher: 'Ưu đãi',
  kCreateNewPass: 'Tạo mật khẩu mới',
  kTitleLinkBank: 'Liên kết thẻ %s',
  kDescriptionLinkBankStart: 'Xác nhận liên kết thẻ của ngân hàng ',
  kDescriptionLinkBankEnd: ' vào Ví Bitback để sử dụng cho các giao dịch.',
  kConditionLink: 'Điều kiện để liên kết thẻ:',
  kFirstNotifyConditionStart: 'Thẻ đã bật chức năng ',
  kFirstNotifyConditionEnd: 'Thanh toán trực tuyến.',
  kSecondNotifyConditionStart: 'Nạp ít nhất ',
  kSecondNotifyConditionCenter: '%s ₫ vào ví ',
  kSecondNotifyConditionEnd: 'để đảm bảo tài khoản thẻ còn hoạt động.',
  kEffective: 'Hiệu \n lực',
  kDateFormat: '--/--',
  kSelectBank: 'Chọn ngân hàng liên kết',
  kMessageTypeBank: 'Nhập tên hoặc mã ngân hàng',
  kMessageTypeCardInfo: 'Nhập thông tin thẻ',
  kTypeCardNum: 'Nhập số thẻ',
  kEffectiveDateInfoCard: 'Ngày hiệu lực (MM/YY)',
  kTypeMoney: 'Nhập số tiền',
  kCardInfoMess: 'Bạn cần nạp tối thiểu 10,000 ₫ để thẻ được liên kết.',
  kLink: 'Liên kết',
  kTakeIdentityPapers: 'Chụp hình giấy tờ tùy thân',
  kTakeIdentity:
      'Bạn cần chụp hình mặt trước và sau của CMND hoặc CCCD hoặc Hộ chiếu',
  kNotProvided: 'Chưa cung cấp',
  kTakePicture: 'Chụp hình',
  kTakeFaceVideo: 'Quay video khuôn mặt',
  kVerifyFace: 'Bạn cần xác thực khuôn mặt của bạn cùng với giấy tờ tùy thân',
  kTakeVideo: 'Quay video',
  kSendIdentity: 'Gửi định danh',
  kFlow: 'Theo',
  kPolicy: ' quy định của NHNN ',
  kRequestIdentity: ', tài khoản ví phải được định danh trước khi sử dụng',
  kSelfIdentity: 'Sử dụng giấy tờ tùy thân hợp lệ của chính bạn',
  kInsideCamera: 'Phải đặt thẻ trong khung camera',
  kNotPhotoIdentity: 'Không sử dụng bản sao của giấy tờ tùy thân',
  kIdentityEKYC: 'Định danh tài khoản (eKYC)',
  kStart: 'Bắt đầu',
  kScanQrCode: 'Quét mã',
  kScanCode: 'Thanh toán',
  kIdentityChecked: 'Căn cước công dân',
  kCaptureDone: 'Đã chụp thành công',
  kVideoFaceTitle: 'Quay video xác thực khuôn mặt',
  kVideoSize: 'Video sẽ có độ dài 5 giây',
  kVideoDescription:
      'Vui lòng giữ gương mặt và mặt trước giấy tờ tùy thân của bạn trước máy quay',
  kVideoTitle: 'Video xác thực khuôn mặt',
  kVideoDone: 'Đã quay thành công',
  kUploading: 'Đang tải dữ liệu...',
  kPleaseWait: 'Vui lòng chờ trong giây lát.',
  kEmptyPromo: 'Chưa có ưu đãi',
  kPromoNew: 'Đổi Rewards để tận hưởng ưu đãi \n ngay hôm nay',
  kExpendable: 'Có thể dùng',
  kUseNow: 'Dùng ngay',
  kHaveUse: 'Đã dùng',
  kLetUse: 'Sử dụng ngay',
  kConfirmVideo: 'Xác nhận video',
  kPleaseConfirmVideo:
      'Vui lòng xác nhận video đã rõ nét, gương mặt và giấy tờ tùy thân có trong hình',
  kIdentityCard: 'Chứng minh nhân dân',
  kFront: 'Mặt trước',
  kPutPaperCenter: 'Vui lòng căn chỉnh giấy tờ vào giữa khung',
  kSelectTypeCard: 'Chọn loại giấy tờ',
  kCitizenIdentity: 'Căn cước công dân',
  kPassport: 'Hộ chiếu',
  kPhotoConfirm: 'Xác nhận hình chụp',
  kEnsureClearPicture:
      'Hãy đảm bảo hình chụp rõ ràng dễ đọc, \nkhông bị mờ tối hay chói sáng',
  kCapture: 'Chụp lại',
  kBackside: 'Mặt sau',
  kRedo: 'Làm lại',
  KTransfersOffChange: 'Chuyển Off-chain',
  KTransfersOnChange: 'Chuyển On-chain',
  kStatus: 'Trạng thái',
  kDoing: 'Đang thực hiện',
  kTransactionId: 'Mã giao dịch',
  kTransactionTime: 'Thời gian giao dịch',
  kReceiveAccount: 'Tài khoản nhận',
  kCompleted: 'Hoàn tất',
  kPayments: 'Hình thức',
  kSuccess: 'Thành công',
  kSendOff: 'Gửi Off-chain',
  kSendOn: 'Gửi On-chain',
  kNote: 'Lưu ý: ',
  kContentNote:
      'Chỉ gửi BTC đến địa chỉ này, việc gửi các loại \ntiền hoặc token khác đến địa chỉ này có thể khiến \nbạn mất tiền và token mà không thể khôi phục',
  kEKYC: 'eKYC',
  kNoteSendOn:
      'Để giảm thiểu rủi ro cho bạn, tính năng “Send \nOn-chain” sẽ mặc định được vô hiệu hóa',
  kNoteEKYC:
      'Bạn cần hoàn thành xác minh tài khoản \n(eKYC) trước khi sử dụng tính năng này',
  kActiveNow: 'Kích hoạt ngay',
  kVerifiNow: 'Xác minh ngay',
  kInformationReceiver: 'Thông tin người nhận',
  kHintInformationReceiver: 'Email / SĐT / Tên tài khoản',
  kNumOfBTC: 'Số lượng BTC',
  kInputNum: 'Nhập số lượng',
  kServiceCharge: 'Phí dịch vụ: ',
  kSendNow: 'Gửi ngay',
  kAddressOnChain: 'Địa chỉ ví On-chain',
  kInputAddress: 'Nhập địa chỉ',
  kTransferFree: 'Chuyển thường (miễn phí)',
  kConfirmEmail: 'Xác thực qua email',
  kOtpSendToMail: 'Nhập mã OTP đã được gửi qua email',
  kVerifyCode: 'Mã xác thực',
  kAuthenSMS: 'Xác thực qua SMS',
  kCheckSMS: 'Kiểm tra tin nhắn để nhận mã OTP',
  kCheckMail: 'Kiểm tra email để nhận mã OTP',
  kToFriend: 'Chuyển đến bạn bè',
  kFriendOfUser: ' (%s/%s đã xác thực)',
  kAll: 'Tất cả',
  kTrustPay: 'Bitback',
  kInputSearch: 'Nhập tên hoặc số điện thoại',
  kNoteUpdateVerify:
      'Để đảm bảo an toàn, vui lòng cập nhật và xác minh \ngiao dịch qua cả email và số điện thoại',
  kSendToFriend: 'Chuyển tiền đến bạn bè',
  kContactOrPhoneNumber: 'Danh bạ hoặc Số điện thoại',
  kBankAccount: 'Tài khoản ngân hàng',
  kATMOrAccountNumber: 'Thẻ ATM hoặc số tài khoản',
  kRecentTransaction: 'Giao dịch gần đây (%s)',
  kDomesticAtm: 'Thẻ ATM nội địa',
  kChange: 'Thay đổi',
  kTypeCreditNumber: 'Nhập số thẻ',
  kCreditCardExpirationDate: 'Ngày hiệu lực',
  kMessageTypeCreditNum: 'Nhập số thẻ ở mặt trước thẻ',
  kChargeMoney: 'Số tiền nạp (đ)',
  kTypeChargeMoney: 'Nhập số tiền nạp',
  kTypeChargeMoneyVnd: 'Nhập số tiền (đ)',
  kTooltipMessage: 'Nhập lời nhắn (tối đa 100 ký tự)',
  kRecommendTrustPay:
      'chưa có tài khoản Bitback. Giới thiệu ngay để được nhận những ưu đãi hấp dẫn.',
  kCancel: 'Hủy bỏ',
  kTransactionDetail: 'Chi tiết giao dịch',
  kAccountTrustPay: 'Tài khoản Bitback',
  kSenderFullName: 'Họ tên người nhận',
  kContactName: 'Tên danh bạ',
  kMethod: 'Phương thức',
  kBankTransfer: 'Chuyển khoản ngân hàng',
  kMoMoTransfer: 'Momo',
  kZaLoTransfer: 'Zalo',
  kDepositIntoTrustPay: 'Nạp tiền vào tài khoản Bitback',
  kCashBack: 'Bitback',
  kTabCashBack: 'Cashback',
  kCashBackExpect: 'Cashback (dự kiến)',
  kUnitVNDC: '%s VNDC',
  kNumCard: 'Số thẻ',
  kRemittanceCode: 'Mã chuyển tiền',
  kDepositIntoBank: 'Nạp tiền qua chuyển khoản ngân hàng',
  kDomesticCard: 'Thẻ ATM nội địa',
  kATMTransfer: 'Thanh toán thẻ ATM nội địa',
  kCreditCardTransfer: 'Thanh toán thẻ tín dụng',
  kAffiliateAccount: 'Tài khoản liên kết',
  kTransferToFriend: 'Chuyển tiền đến bạn bè',
  kTransferBank: 'Chuyển tiền qua tài khoản ngân hàng',
  kAccountNumber: 'Số tài khoản',
  kBank: 'Ngân hàng',
  kMessage: 'Lời nhắn',
  kSaveInfoForLater: 'Lưu thông tin cho lần sử dụng sau',
  kNumATM: 'Số thẻ ATM',
  kFullNameOwnerCard: 'Họ tên chủ thẻ',
  kEffectiveDate: 'Ngày hiệu lực',
  kMyCard: 'Thẻ của tôi',
  kOther: 'Khác',
  kSupport: 'Hỗ trợ',
  kConfirmDelivery: 'Xác nhận đã chuyển',
  kInfoTransfer: 'Thông tin chuyển khoản',
  kNoteTransfer:
      'Vui lòng chuyển khoản số tiền muốn nạp tới thông \ntin tài khoản bên dưới:',
  kAccountOwner: 'Chủ tài khoản',
  kBranch: 'Chi nhánh',
  kContent: 'Nội dung',
  kSystemChecking:
      'Hệ thống đang kiểm tra trạng thái \nlệnh chuyển tiền. Vui lòng chờ \ntrong giây lát...',
  kSystemCheckingFail:
      ' Hệ thống vẫn chưa ghi nhận lệnh \nchuyển tiền của bạn. Tài khoản \ncủa bạn sẽ được ghi có ngay khi \nhệ thống ghi nhận thành công',
  kTrade: 'Giao dịch',
  kChooseWithdrawal: 'Chọn nơi rút về',
  kSelectedBank: 'Chọn ngân hàng',
  kTypeAccountNumber: 'Nhập số tài khoản',
  kWithdrawalMoney: 'Số tiền rút (₫)',
  kWithdrawalIntoBank: ' Rút tiền về tài khoản ngân hàng',
  kWithdrawalIntoDomesticATM: ' Rút tiền về thẻ ATM nội địa',
  kWithdrawalIntoMyCard: ' Rút tiền về tài khoản liên kết',
  kIdentified: 'Đã định danh',
  kInfo: 'Thông tin',
  kMyProfile: 'Hồ sơ của tôi',
  kChangePassword: 'Đổi mật khẩu',
  kCardManagement: 'Quản lý thẻ',
  kFaceId: 'Face ID',
  kAllowNotify: 'Cho phép thông báo',
  kTermProfile: 'Điều khoản và điều kiện',
  kIdentifyAccount: 'Định danh tài khoản (eKYC)',
  kSecret: 'Bảo mật & Định danh',
  kLogout: 'Đăng xuất',
  kTrustPayEmptyMessage:
      'Xác minh thông tin để kích hoạt thẻ Bitback và sử dụng các dịch vụ',
  kAssociateCardEmptyMessage:
      'Liên kết tài khoản ngân hàng để có thể nạp và rút tiền nhanh chóng',
  kTrustPayCard: 'Thẻ Bitback',
  kAssociateCard: 'Thẻ liên kết',
  kCreditNumMasked: '•••• •••• •••• ••••',
  kAssociateSuccess: 'Liên kết tài khoản \n thành công',
  kCancelAssociateSuccess: 'Hủy liên kết thẻ \n thành công',
  kReceiveBankInfo: 'Thông tin ngân hàng nhận',
  kTitleInputCreditOrAccount: 'Nhập số thẻ hoặc số tài khoản',
  kHintInputCreditOrAccount: 'Số thẻ hoặc số tài khoản',
  kTypingReceiveName: 'Nhập họ tên người nhận',
  kMessageSendViaBank: 'Nhập lời nhắn (không dấu và các ký tự đặc biệt)',
  kBuyNow: 'Mua ngay',
  kPay: 'Thanh toán',
  kPromotion: 'Ưu đãi',
  kContact: 'Liên hệ',
  kRefundPayment: 'Thanh toán hoàn tiền',
  kSymbol: '(%s)',
  kContentIntroduce:
      'Giới thiệu một người bạn đăng ký Bitback, bạn sẽ nhận được %s Satoshi(SAT) và người bạn giới thiệu sẽ nhận được %s Satoshi(SAT)',
  kIntroduceSat: 'Nhập mã giới thiệu để nhận %s Satoshi',
  kReferralLink: 'Đường dẫn',
  kSocialShare: 'Chia sẻ mạng xã hội',
  kReceived: 'Bạn đã nhận',
  kEmail: 'Email',
  kInputEmail: 'Nhập email',
  kSaveInfo: 'Lưu thông tin',
  kPhotoLibrary: 'Thư viện ảnh',
  kCamera: 'Camera',
  kExit: 'Thoát',
  kOldPassword: 'Mật khẩu cũ',
  kErrorConfirmPassword: 'Xác nhận mật khẩu không chính xác',
  kNotEnoughBalance: 'Số dư của bạn không đủ để \nthực hiện giao dịch',
  kRechargeMore: 'Nạp thêm tiền',
  kCancelTransaction: 'Hủy giao dịch',
  kInputQrCode: 'Đưa mã QR vào khung',
  kPaymentCode: 'Mã thanh toán',
  kAutomaticUpdate: 'Tự động cập nhật sau %ss',
  kReNew: 'Làm mới',
  kPromoCode: 'Mã ưu đãi',
  kChooseCode: 'Chọn mã',
  kPaymentQrCodeTitle: 'Chỉ cung cấp mã thanh toán cho thu ngân',
  kFree: 'Miễn phí',
  kWithDraw: 'Rút',
  kWithExchange: 'Quy đổi',
  kAnnualFee: 'Phí thường niên',
  kAssociateBank: 'Ngân hàng liên kết',
  kActivationDate: 'Ngày kích hoạt',
  kAssociateDate: 'Ngày liên kết',
  kCancelAssociate: 'Hủy liên kết',
  kAssociateCardDetail: 'Chi tiết thẻ liên kết',
  kConfirmDeleteCard:
      'Bạn có chắc muốn ngừng liên kết ví Bitback với tài khoản ngân hàng?',
  kAccount: 'Tài khoản',
  kCashbackAvailable: 'Cashback khả dụng',
  kCashbackPending: 'Cashback chờ duyệt',
  kValueCashBack: '%s triệu tiền đã hoàn',
  kCategory: 'Danh mục',
  kPopular: 'Phổ biến',
  kSort: 'sắp xếp',
  kAppetizer: 'Khai vị',
  kOldCustomer: 'Khách hàng cũ',
  kNewCustomer: 'Khách hàng mới',
  kReadBeforeBuy: 'Đọc kỹ trước khi mua sắm bạn nhé!',
  kRefundWhen: 'Hoàn tiền khi nào?',
  kCashBackDetail: 'Chi tiết Cashback',
  kContentRefund:
      'Hoàn tiền được áp dụng trên số tiền cuối cùng sau khi đã trừ đi khuyến mãi, giảm giá, thuế VAT và chi phí vận chuyển.',
  kContentBill:
      'Đơn hàng sẽ được ghi nhận sau 24-48h kể từ lúc bạn đặt hàng thành công.',
  kContentTimeRefund:
      'Nhận hoàn tiền vào 60-90 ngày tiếp theo kể từ ngày đơn hàng được ghi nhận trên app Bitback.',
  kReadCarefully: 'Đọc kỹ trước khi mua sắm',
  kRefundTime: 'Thời gian hoàn tiền',
  kImportantRules: 'Quy định quan trọng cần chú ý tránh mất hoàn tiền',
  kRefundsNotAccept: 'Không chấp nhận hoàn tiền',
  kContentStore:
      'Trong một lần thanh toán đơn hàng: Nếu cùng một Shop, có thể mua nhiều sản phẩm khác nhau. Nếu khác Shop, nên tách đơn hàng hoặc mua với hình thức thanh toán trả trước.',
  kContentMoneyBag:
      'Mỗi lần thành toán chỉ được hoàn tiền tối đa 27,500 ₫, bạn nên tách đơn hàng thanh toán nhiều lần.',
  kContentPicture:
      'Không click vào Banner quảng cáo của thương hiệu sau khi chuyển từ ứng dụng Bitback qua.',
  kContentCart:
      'Không thêm sản phẩm vào GIỎ HÀNG trên website hoặc ứng dụng của thương hiệu TRƯỚC KHI Click từ Bitback qua.',
  kContentComputer:
      'Mỗi Click Mua Ngay chuyển qua ứng dụng chỉ được HOÀN THÀNH 1 LẦN THANH TOÁN. Mở lại ứng dụng Bitback để mua đơn hàng mới.',
  kContentIncorrect1:
      'Các trường hợp tự tạo shop mua hàng, mua đi bán lại số lượng lớn sẽ không được hoàn tiền hoặc bị khóa tài khoản.',
  kContentIncorrect2:
      'Chỉ áp dụng hoàn tiền khi mua hàng qua ỨNG DỤNG. Hãy cài đặt ứng dụng trước khi mua.',
  kContentIncorrect3:
      'Hủy đơn, đổi trả, bom hàng hoặc tự tạo Shop và mua hàng để nhận hoa hồng',
  kPizzaVoucher: 'Ưu đãi The Pizza Company',
  kNotAddProductBefore: 'Không thêm sản phẩm vào giỏ hàng từ trước',
  kNotPayMultipleOrders: 'Không thanh toán nhiều đơn hàng liên tiếp',
  kContentNotAddProductBefore:
      'Nếu bạn đã thêm sản phẩm vào giỏ hàng \ntrước khi chuyển từ Bitback qua đối tác, \nviệc hoàn tiền sẽ không được áp dụng.',
  kContentNotPayMultipleOrders:
      'Mỗi Click MUA NGAY chỉ ghi nhận hoàn tiền \ncho MỘT lần thanh toán. Quay lại Bitback \nnếu bạn muốn mua tiếp.',
  kOkCreateCart: 'OK, Tạo giỏ hàng mới',
  kOKSlowlyButSurely: 'OK, Chậm mà chắc',
  kSelectCategory: 'Chọn danh mục',
  kA2Z: 'Tên A-Z',
  kZ2A: 'Tên Z-A',
  kHighCashBack: 'Cashback cao',
  kSearch: 'Tìm kiếm',
  kSearchNear: 'Tìm kiếm gần đây',
  kClose: 'Đóng',
  kCancelOrder: 'Xác nhận hủy',
  kCancelSellEgg: 'Hủy',
  kNotFound: 'Không có kết quả phù hợp',
  kCheckSearch: 'Vui lòng kiểm tra chính tả\nhoặc sử dụng các gợi ý',
  kSummary: 'Tổng giá trị',
  kRewardPending: 'Thưởng chờ duyệt',
  kOpenVNDC: 'Bạn chưa có ví nhận Bitcoin?',
  kOpenBitCoin: 'Mở tài khoản ONUS\nđể nhận ngay 200,000 VNDC',
  kGeneralRules: 'Quy định chung',
  kTimeRefund: 'Thời gian hoàn tiền',
  kRefund_1: 'Hoàn tiền được áp dụng trên số tiền cuối cùng sau khi đã',
  kRefund_2: ' trừ đi khuyến mãi, giảm giá, thuế VAT và chi phí vận chuyển.',
  kRefund_3: 'Đơn hàng sẽ được ghi nhận sau',
  kRefund_4: ' 24-48h ',
  kRefund_5: 'kể từ lúc bạn đặt hàng thành công.',
  kRefund_6: 'Nhận hoàn tiền vào',
  kRefund_7: ' 60-90 ngày tiếp theo',
  kRefund_8: ' kể từ ngày đơn hàng được ghi nhận trên app Bitback.',
  kRefund_9:
      'Trong một lần thanh toán đơn hàng: Nếu cùng một Shop, có thể mua nhiều sản phẩm khác nhau. ',
  kRefund_10:
      'Nếu khác Shop, nên tách đơn hàng hoặc mua với hình thức thanh toán trả trước.',
  kRefund_11: 'Mỗi lần thành toán chỉ được hoàn tiền tối đa ',
  kRefund_12: '27,500 ₫,',
  kRefund_13: ' bạn nên tách đơn hàng thanh toán nhiều lần.',
  kRefund_14: 'Không click vào Banner quảng cáo của thương hiệu ',
  kRefund_15: 'sau khi chuyển từ ứng dụng Bitback qua.',
  kRefund_16: 'Không thêm sản phẩm vào GIỎ HÀNG ',
  kRefund_17: 'trên website hoặc ứng dụng của thương hiệu ',
  kRefund_18: 'TRƯỚC KHI Click từ Bitback qua.',
  kRefund_19: 'Mỗi Click Mua Ngay ',
  kRefund_20: 'chuyển qua ứng dụng chỉ được ',
  kRefund_21: 'HOÀN THÀNH 1 LẦN THANH TOÁN. ',
  kRefund_22: 'Mở lại ứng dụng Bitback để mua đơn hàng mới.',
  kImportants: 'Quy định quan trọng cần chú ý tránh mất hoàn tiền',
  kNotRefund: 'Không chấp nhận hoàn tiền',
  kCountDown: 'Bảng xếp hạng',
  kRewardMe: 'Ưu đãi của tôi',
  kWantBTC: 'Số Satoshi muốn rút',
  kWantTransfer: 'Số lượng %s muốn rút',
  kWantBBC: 'Số lượng BBC muốn rút',
  kEmailOrPhone: 'Nhập email hoặc sđt',
  kHasAmount: 'Bạn đang có',
  kRewardMin: 'Số tối thiểu trên một giao dịch là %s',
  kLimitReward: 'Hạn mức trong ngày là %s',
  kEmailTransfer: 'Email hoặc SĐT đăng nhập ví %s',
  kFeeTransfer: 'Phí giao dịch: %s',
  kTotalTransfer: 'Tổng số lượng(đã báo gồm phí giao dịch)',
  kAddressKai: 'Địa chỉ ví',
  kCheckVNDC: 'Kiểm tra ví VNDC',
  kCampaign: 'Chiến dịch',
  kWhatBlockChain: 'Công nghệ Blockchain là gì?',
  kTPP: '%s TPP',
  kDoMission: 'Làm nhiệm vụ',
  kErrorOtp: 'Mã OTP không chính xác, hãy thử lại',
  kMinimumToRedeem: 'Số tối thiểu để đổi thưởng là 20,000 Sat',
  kSpin: 'Vòng quay',
  kGameChicken: 'BitFarm',
  kDescriptionPending: 'Tài khoản của bạn đang chờ xác thực\nCảm ơn!',
  kDescriptionAccept: 'Tài khoản của bạn đã được xác thực\nCảm ơn!',
  kDescriptionReject: 'Xác thực không thành công\nVui lòng thử lại',
  kNotData: 'Không có dữ liệu',
  kDashboard: 'Dashboard',
  kSum: 'Tổng',
  kPaid: 'Đã thanh toán',
  kRosesThisMonth: 'Hoa hồng tháng này',
  kBonus: 'Thưởng',
  kGD: 'GD',
  kTransactionHistory: 'Lịch sử giao dịch',
  kApproved: 'Đã duyệt',
  kCheckingProgress: 'Đang đối soát',
  kPoundage: 'Tiền Hoa hồng',
  kDepositSat: 'Số SAT muốn nạp',
  kTitleDeposit: 'Nạp',
  kDetailDeposit: 'Chi tiết nạp',
  kMain: 'Trang chủ',
  kFarm: 'Trang trại',
  kChickenMarket: 'Chợ gà',
  kHistoryFarm: 'Giao dịch',
  kLevelFarm: 'Xếp hạng',
  kOtherFarm: 'Thêm',
  kCollect: 'Bộ sưu tập',
  kNewEvent: 'Sự kiện',
  kError: 'Có lỗi xảy ra vui lòng thử lại.',
  kEggHatch: 'Trứng sắp nở rồi!',
  kFriend: 'Bạn bè',
  kCodeIntroduce: 'Mã giới thiệu',
  kGiftFriend: 'Phần thưởng giới thiệu bạn bè',
  kTime: 'Thời gian',
  kFriendKyc: 'Bạn bè đã KYC',
  kMember: 'Thành viên',
  kRank: 'Hạng',
  kUnregisteredKyc: 'Chưa KYC',
  kRegisteredKyc: 'Đã KYC',
  kOpenBitback: 'Giới thiệu bạn bè',
  kGetNow: 'nhận ngay',
  kCopied: 'Đã sao chép',
  kCodeIntroduceNotFound: 'Không tìm thấy mã giới thiệu',
  kNewUpdate: 'Bản cập nhật mới đã sẵn sàng!',
  kUpdateNow: 'Cập nhật ngay',
  kComeBackLate: 'Hãy trở lại sau nhé!',
  kSystemUpgrades:
      'Chúng tôi xin lỗi cho sự bất tiện này. Chúng tôi đang nâng cấp hệ thống để giúp trải nghiệm được tốt hơn.',
  kIncorrectSatoshi: 'SAT bạn nhập không chính xác',
  kCheckSatoshi: 'Kiểm tra lại số Satoshi',
  kCashbackAvailableInvalid: 'Bạn không đủ số Sat để mua',
  kInvalidCredentials: 'Mật khẩu bạn nhập không chính xác',
  kPhoneExist: 'Số điện thoại đã được sử dụng ở tài khoản khác',
  kEggInvalid: 'Trứng không hợp lệ',
  kBadRequest: 'Máy chủ đang bận, vui lòng thử lại sau',
  kAccountTemporarilyLocked: 'Tài khoản của bạn đã bị khoá.',
  kUnauthorized: 'Phiên đăng nhập đã hết hạn',
  kCheckPhoneNumber: 'Kiểm tra lại số điện thoại',
  kPhoneEmpty: 'Số điện thoại không để trống.',
  kLoginGoogle: 'Đăng nhập qua Google',
  kLoginFacebook: 'Đăng nhập qua Facebook',
  kCheckCodeIntroduce: 'Kiểm tra lại mã giới thiệu',
  kCheckEmail: 'Kiểm tra lại email',
  kInputAmount: 'Nhập số lượng để đổi thưởng',
  kValidSat: 'Satoshi không chính xác',
  kHoldMin: 'Duy trì số dư tối thiểu: %s',
  kValidAmount: 'Số %s bạn đổi không khả dụng',
  kTransferUnLimit: 'Giao dịch không vượt quá %s',
  kValidAcount: 'Tài khoản ví %s không hợp lệ.\n Vui lòng kiểm tra lại',
  kValidEmail: 'Email không tồn tại',
  kCheckInfo: 'Kiểm tra lại thông tin',
  kAccountInvalid: 'Tài khoản không chính xác',
  kInvalidBalance: 'Số dư không khả dụng',
  kAmountInvalidMin: 'Số dư tối thiểu không khả dụng',
  kAmountInvalidMax: 'Giao dịch không vượt quá %s',
  kAmountInvalidDay: 'Vượt quá hạn mức rút tối đa trong ngày',
  kAmountInvalid: 'Giao dịch không hợp lệ',
  kAccountTransferInvalid: 'Tài khoản không chính xác',
  kHandleInvalid: 'Giao dịch xử lý lỗi',
  kAmountInvalidMonth: 'Vượt quá hạn mức rút tối đa trong tháng',
  kHasTransactionPending: 'Bạn có giao dịch đang được xử lý',
  kTutorialStep: 'Hướng dẫn bạn bè 3 bước nhận thưởng',
  kTutorialStep1: 'Mời bạn bè tải ứng dụng Bitback theo đường dẫn bên dưới',
  kTutorialStep2: 'Đăng ký với mã giới thiệu',
  kTutorialStep3: 'Định danh (KYC) và Nhận thưởng',
  kDataNotFound: 'Dữ liệu trống',
  kSomeWentWrong: 'Có lỗi xảy ra. Vui lòng thử lại sau\nhoặc liên hệ hỗ trợ.',
  kTooManyRequest: 'Quá nhiều yêu cầu',
  kBodyRequire: 'Thiếu thông tin',
  kPhoneInvalid: 'Số điện thoại không đúng',
  kTitlePhoneExists: 'Số điện thoại bạn nhập',
  kPhoneExists: 'đã được dùng cho tài khoản khác.',
  kTypeRequire: 'Chưa chọn loại tài khoản',
  kEmailExists: 'Địa chỉ Email bạn nhập',
  kMgsEmailExists: 'đã được dùng cho tài khoản khác.',
  kPassCodeInvalid: 'Mật mã không đúng',
  kFullNameRequire: 'Chưa nhập họ tên',
  kTokenInvalid: 'Phiên đăng nhập không đúng',
  kOtpInvalid: 'Mã xác thực không đúng',
  kEmailInvalid: 'Email đã được sử dụng',
  kCashBackAvailable: 'kCashBackAvailable',
  kAccountLocked: 'Tài khoản của bạn đã bị khoá.',
  kUnAuthorized: 'Phiên đăng nhập hết hạn. Vui lòng đăng nhập lại.',
  kTransactionPending: 'Bạn có 1 giao dịch đang chờ xử lý',
  kTitleExchange: 'Quy đổi tài sản',
  kRatioExchange: 'Tỉ lệ quy đổi: 1 %s ~ %s %s',
  kExchangeTo: 'Sang',
  kExchangeFrom: 'Quy đổi từ',
  kSelectedExchange: 'Chọn tài sản quy đổi',
  kAmountExchange: 'Nhập số lượng %s quy đổi',
  kMinAmountExchange: 'Số lượng quy đổi tối thiểu: %s',
  kMaxAmountExchange: 'Số lượng quy đổi tối đa: %s',
  kValidAmountExchange: 'Số dư không khả dụng',
  kValidInputAmount: 'Số %s bạn nhập không chính xác',
  kButtonExchange: 'Quy đổi trong (%ss)',
  kUpdatePriceExchange: 'Cập nhật giá',
  kEarnSat: 'Earn Satoshi',
  kTimeRemaining: 'Thời gian còn lại',
  kHasSatoshi: 'Số satoshi đang có',
  kSatReceiver: 'Số satoshi trả thưởng',
  kProgramEnd: 'Chương trình đã kết thúc',
  kLastGame: 'Đã diễn ra(%s)',
  kGoingGame: 'Đang diễn ra(%s)',
  kInformation: 'Thông tin',
  kUserInformation: 'Thông tin đăng ký',
  kPrizes: 'Giải thưởng',
  kRemaining: 'Còn lại ',
  kEndGame: 'Đã kết thúc',
  kPlayFree: 'CHƠI MIỄN PHÍ',
  kPlayNow: 'CHƠI NGAY',
  kFeePlayGame: 'Phí %s',
  kRanking: 'Hạng',
  kPlayer: 'Người chơi',
  kScore: 'Điểm',
  kFriends: 'Danh sách bạn bè',
  kFacebook: '\t Facebook',
  kZalo: '\t Zalo',
  kTelegram: '\t Telegram',
  kWheelDaily: 'VÒNG QUAY HÀNG NGÀY',
  kWheel: 'QUAY, QUAY, QUAY',
  kReceiverReward: 'nhận thưởng\t',
  kTitleWheel:
      'Mỗi ngày khi đăng nhập vào ứng dụng \nbạn sẽ nhận được một lượt quay \nđể nhận thưởng ',
  kTitle2Wheel: 'sẽ nhận được một lượt quay để',
  kHasWheel: 'Bạn còn 1 lượt quay',
  kEndWheel: 'Bạn hết lượt quay',
  kWheelNow: 'Quay ngay',
  kSelectCashBack: 'Chọn loại tài sản muốn rút',
  kDraw: 'Rút',
  kTopBalance: 'Số dư %s',
  kButtonActivated: 'Kích hoạt',
  kAccountUnActivated: 'Tài khoản bạn chưa kích hoạt',
  kAccountRejected: 'Tài khoản bạn bị từ chối',
  kConfirmAgain: 'Xác thực lại',
  kAccountPending: 'Tài khoản bạn đang được xử lý',
  kAccountIdentifier: 'Tài khoản bạn chưa định danh',
  kIdentifier: 'Định danh',
  kHarvest: 'Thu hoạch',
  kHarvestEggBreed: 'Thu hoạch trứng ấp',
  kBreed: 'Phối giống',
  kBuyEgg: 'Mua trứng',
  kBuyChicken: 'Mua gà',
  kEmptyRooster: 'Hãy mua vài anh gà trống nhé!',
  kEmptyBreed: 'Không có cặp gà nào\n đang phối giống',
  kEmptyEgg: 'Hãy mua vài quả trứng\nđể ấp hoặc phối giống nhé!',
  kEmptyChicken: 'Hãy mua vài chú gà nhé!',
  kBreeding: 'Đang phối',
  kSelling: 'Đang bán',
  kForSell: 'Rao bán',
  kOpenEgg: 'Mở trứng',
  kPriceBBC: ' %s BBC',
  kTitleSellOk: 'Rao bán thành công',
  kTitleSellChicken: 'Chợ gà với giá',
  kMgsChicken: 'Gà %s lên chợ gà với giá',
  kYouReceiver: 'Chúc mừng! Bạn nhận được',
  kFeeBBC: 'Phí ~ %s BBC',
  kFeeRatio: 'Phí ~ %s%',
  kDetailChicken: 'Đặc tính',
  kChicken: 'Gà %s',
  kIdChicken: 'ID Gà',
  kTitleLevel: 'Cấp độ',
  kValueLevel: 'Level %s',
  kProductivityDaily: 'Năng suất mỗi ngày',
  kRate: 'Lãi suất dự kiến',
  kTimeLevel: 'Thời gian lên cấp',
  kValueTimeLevel: '%s Ngày',
  kLongevity: 'Tuổi thọ',
  kLifeChicken: 'Thời gian sống',
  kRemainingBreed: 'Số lần phối giống còn lại',
  kBuy: 'Mua',
  kMaxLevel: 'Bạn đã ở level cao nhất',
  kPrepareUpLevel: 'Chuẩn bị lên level %s',
  kRemainingLevel: 'Còn %s ngày để lên level %s',
  kProductNotExists: 'Sản phẩm bạn mua không còn tổn tại',
  kConfirmBuyChicken: 'Xác nhận thanh toán mua gà',
  kConfirmBuyEgg: 'Xác nhận thanh toán mua trứng',
  kTransactionSuccess: 'Giao dịch thành công',
  kSell: 'Bán',
  kSellEgg: 'Rao bán trứng',
  kSetPrice: 'Đặt giá',
  kSellYellowEgg: 'Bán trứng vàng',
  kAmount: 'Số lượng',
  kInputEgg: 'Nhập số trứng',
  kTurnover: 'Doanh thu',
  kLabelNote: 'Ghi chú: ',
  kTitlePass: 'Mật khẩu không đúng',
  kTitleChangePass: 'Mật khẩu hiện tại không đúng',
  kMgsChangePass: 'không đúng, vui lòng nhập lại.',
  kInputAgain: 'Vui lòng nhập lại.',
  kVerifyPhoneFail: 'Xác thực số điện thoại thất bại',
  kSelectToken: 'Bấm vào để lựa chọn',
  kMaxSellEgg: 'Vượt quá số trứng tối đa %s',
  kMinSellEgg: 'Số trứng tối thiểu là %s',
  kAmountEgg: 'Số lượng phải là bội số của %s',
  kRankFarm: 'Bảng xếp hạng Trang Trại',
  kOwnerFarm: 'Chủ trang trại',
  kQuantityChicken: 'Số gà',
  kQuantityEgg: 'Số trứng',
  kQuantityYellowEgg: 'Số trứng vàng',
  kTypeTransaction: 'Loại giao dịch',
  kDone: 'Đã thực hiện',
  kForSellChicken: 'Rao bán gà',
  kProduct: 'Sản phẩm',
  kInvalidPrice: 'Kiểm tra lại giá bán',
  kPrice: 'Giá bán phải là bội số 10',
  kMinPrice: 'Giá bán không được nhỏ hơn 40 BBC',
  kMaxPrice: 'Giá bán không vượt quá 1.000.000 BBC',
  kFeeBreed: 'Chi phí phối giống',
  kTimeBreed: 'Thời gian phối giống',
  kStartBreed: 'Bắt đầu phối giống',
  kSelectRooster: 'Chọn gà trống',
  kSelectChicken: 'Chọn gà mái',
  kEmptySlot: 'Trang trại của bạn còn thiếu %s chỗ để mở trứng ấp',
  kChooseChicken: 'Chọn cặp gà để phối giống nhé',
  kChoose: 'Chọn',
  kChooseAgain: 'Chọn lại',
  kFeeBreeding: 'Chi phí',
  kConfirmBreeding: 'Xác nhận phối giống',
  kTitleBreed:
      'Cặp gà bạn chọn để phối giống không cùng loại. Hãy chọn lại nhé!',
  kPriceSell: 'Giá',
  kSellOne: 'Mỗi lượt mua được %s quả trứng',
  kBuyChickenOnMarket: 'Mua trên chợ gà',
  kBuyFromBitBack: 'Mua từ Bitfarm',
  kChooseBuyEgg: 'Chọn nơi mua trứng',
  kEggBreed: 'Trứng ấp',
  kInputBBC: 'Nhập số BBC',
  kAgreeSell: 'Đồng ý bán',
  kConfirmBuy: 'Xác nhận mua',
  kSellPlaceChicken: 'Bạn muốn mua thêm chỗ nuôi gà',
  kThank: 'Xin cảm ơn!',
  kTransactionLater: 'Hãy thực hiện lại sau vài phút nhé',
  kTransactionFail: 'Giao dịch thất bại',
  kHasPlaceChicken: 'Bạn đã có thêm 1 chỗ nuôi gà',
  kBuySlot: 'Mua thêm chỗ',
  kFullSlot: 'Rất tiếc! Trang trại của bạn\nhiên không còn đủ chỗ chứa.',
  kBuyEggPending: 'Lệnh mua đang chờ xử lý.\nXin cám ơn!',
  kHasAccountYet: 'Bạn đã có tài khoản %s chưa?',
  kTransferBitBack: 'Để rút tài sản từ Bitback',
  kNeedAccount: 'bạn cần có tài khoản %s',
  kHasAccount: 'Tôi đã có tài khoản %s',
  kNoHasAccount: 'Tôi chưa có tài khoản %s',
  kWalletPayme: 'Payme',
  kMinAmountPayme: 'Số Satoshi không nhỏ hơn 10,000',
  kMaxAmountPayme: 'Số Satoshi không vượt quá 1,000,000',
  kPendingTransactionPayme: 'Bạn đang có giao dịch đang chờ xử lí.',
  kConfirmNotTransaction: 'Xác nhận bạn chưa thanh toán',
  kCancelTransactionPayme: 'Xác nhận bạn chưa thanh toán',
  kTransactionPayme: 'Nếu đã thanh toán, vui lòng',
  kAwaitSystemPayme: 'đợi hệ thống xác nhận.',
  kAwaitPayme: 'Tiếp tục đợi',
  kMax: 'Max',
  kCancelPayme: 'Xác nhận hủy',
  kQuantityInvalid: 'Có lỗi xảy ra vui lòng thử lại sau.',
  kPriceSellEgg: '%s Trứng = ',
  kBuyEggLater: 'Chưa đến lượt mua Trứng gà  mái',
  kBuyEggRoosterLater: 'Chưa đến lượt mua Trứng gà trống',
  kPleaseBackCome: 'Vui lòng quay lại sau.',
  kNewFeature: 'Tính năng đang phát triển',
  kMaintanceFeature: 'Tính năng đang bảo trì',
  kMessageBuyEggLater: 'Quay lại sau',
  kTimeOpenEgg: 'Đã đến giờ mở trứng',
  kOpen: 'Mở',
  kFeatureUpdate: 'Tính năng đang được cập nhật',
  kNotEnoughSat: 'Bạn không đủ satoshi để mua.',
  kNotEnoughBBC: 'Bạn không đủ BBC để mua.',
  kAddSat: 'Vui lòng nạp thêm!',
  kAwaitOpenEgg: 'Đừng bán trứng vội\n Hãy kiên nhẫn chờ trứng nở nhé',
  kCongHarvest: 'Chúc mừng bạn thu hoạch được',
  kNumberEgg: '+%s Trứng Vàng',
  kBuyYellowEggBitback: 'Bán trứng cho Bitback thành công',
  kPleaseLater: 'Xin vui lòng quay lại trong',
  kTransactionFailPurchase:
      'Giao dịch thất bại!\nHãy thực hiện lại sau vài phút\nXin cảm ơn!',
  kPendingTransactionPurchase:
      'Đang thực hiện giao dịch\nVui lòng chờ trong giây lát!',
  kLockExchange: 'Tính năng đang tạm khóa',
  kLoginWith: 'Đăng nhập với',
  kSkipLogin: 'Bỏ qua',
  kExitAccount: 'Thoát tài khoản',
  kSignIn: 'Đăng nhập',
  kPaymentPayme: 'Cổng thanh toán Payme',
  kFaceIdUnActivated: 'Tính năng Face ID chưa được kích hoạt',
  kTouchIdUnActivated: 'Tính năng Touch ID chưa được kích hoạt',
  kLaterSetting: 'Kích hoạt sau trong phần bảo mật.',
  kEnableTouchId: 'Bật Touch ID/Face ID',
  kDisableTouchId: 'Tắt Touch ID/Face ID',
  kCheckPassCode: 'Kiểm tra lại mật khẩu',
  kSelectBiometric: 'Chọn hình thức xác thực',
  kTotalEgg: 'Tổng: %s',
  kQuestion: 'Giải trí & Nhiệm vụ nhận thưởng',
  kLikeGame: 'Trò chơi được yêu thích',
  kTimeGame: 'Còn lại',
  kUserGame: 'Người chơi',
  kRewardGame: 'Phần thưởng',
  kDescriptionCampaign: 'Mở tài khoản ngân hàng',
  kTabbarGame: 'Trò chơi',
  kTabbarwallet: 'Ví',
  kTabbarLaunchpad: 'Launchpad',
  kFirstMission: 'Nhiệm vụ đầu tiên',
  kDescriptionMission:
      'Xác thực số điện thoại để nhận thưởng %s SAT và tiếp cận toàn bộ tính năng của Bitback.',
  kDeviceUnSupport: 'Thiết bị không hỗ trợ tính năng này',
  kSelectMethod: 'Chọn phương thức thanh toán',
  kUnlimitedPlay: 'Không giới hạn lượt chơi',
  kLimitedPlay: '1 lượt chơi',
  kAvailableBBC: 'Số dư khả dụng: %s',
  kPayBBC: 'Thanh toán với BBC',
  kNext: 'Tiếp theo',
  kInvalidOtp: 'Mã xác thực không chính xác',
  kExpiresOtp: 'Mã xác thực đã hết hạn',
  kTryAgainOtp: 'Vui lòng gửi lại mã xác thực để thử lại.',
  kTitleReferralReward: 'Mã giới thiệu nhận thưởng',
  kInputReferralReward: 'Mã giới thiệu | Email | Số điện thoại',
  kReceiverReferralReward: 'Nhập Mã giới thiệu | Email | Số điện thoại',
  kGetReferralReward: 'để nhận ngay ',
  kOtpVerification: 'Mã xác thực OTP',
  kEnterOtp: 'Vui lòng nhập mã xác thực gồm 4 chữ số',
  kOtpSentEmail: 'đã được gửi đến email',
  kContentOtpPhone: 'Vui lòng nhập mã xác thực gồm 6 chữ số',
  kContent2OtpPhone: 'đã được gửi đến số điện thoại %s',
  kInvalidPass: 'Xác nhận mật khẩu không trùng khớp',
  kInvalidNumberPass: 'Mật khẩu phải đủ 6 chữ số',
  kCreateAccountSuccess: 'Tạo tài khoản thành công',
  kWellComeMember: 'Xin chào thành viên mới!',
  kInputPassAgain: 'Nhập lại mật khẩu',
  kInputReferralAgain: 'không đúng, vui lòng nhập lại.',
  kVerifyPhoneSuccess: 'Xác thực số điện thoại thành công',
  kRewardPhone: 'bạn nhận được ',
  kInvalidOtpPhone: 'Mã xác thực không chính xác',
  kTitleVerifyOtp: 'Mã xác thực OTP',
  kInvalidPhone: 'Số điện thoại không tồn tại',
  kManyRequestOtp: 'Bạn đã gửi yêu cầu quá nhiều lần\n\nVui lòng thử lại sau.',
  kTitleVerifyPhone: 'Vui lòng xác thực số điện thoại',
  kVerifyPhoneReward: 'để nhận thưởng',
  kDescriptionVerify: 'và tiếp cận toàn bộ tính năng của Bitback.',
  kTryAgain: 'Vui lòng thử lại.',
  kTryAgain2: 'để thử lại',
  kBuyHatchingEgg: 'Mua trứng ấp',
  kMyWallet: 'Ví của bạn',
  kInWallet: 'Tài sản trong ví',
  kPendingWallet: 'Chờ duyệt',
  kAmountDeposit: 'Số lượng muốn nạp',
  kMinDeposit: 'Số lượng tối thiểu: %s',
  kMaxDeposit: 'Số lượng tối đa trong một giao dịch: %s',
  kMinTradeDeposit: 'Giao dịch tối thiểu: %s',
  kPayDeposit: 'Số tiền cần thanh toán',
  kMethodPay: 'Phương thức thanh toán',
  kPendingPayment: 'Bạn có 1 giao dịch đang chờ xử lý',
  kMoreDetail: 'Chi tiết',
  kWantWithdraw: 'Số lượng muốn rút',
  kMoneyWithdraw: 'Số dư khả dụng: %s',
  kTodayWithdraw: 'Hạn mức rút tối đa trong ngày: %s',
  kLocalWithdraw: 'Chọn nơi rút về',
  kMyPerson: 'Hồ sơ của tôi',
  kIntroFriend: 'Giới thiệu bạn bè',
  kStatistical: 'Thống kê',
  kVerifyPhone: 'Xác thực số điện thoại',
  kChangePass: 'Đổi mật khẩu',
  kEnableNoti: 'Cho phép thông báo',
  kLanguage: 'Ngôn ngữ',
  kTermAndPolicy: 'Điều khoản và chính sách',
  kCommunityBitback: 'Cộng đồng Bitback',
  kTouchIdFaceId: 'Touch ID/Face ID',
  kNowPass: 'Mật khẩu hiện tại',
  kConfirmNewPass: 'Xác nhận mật khẩu mới',
  kTtInvalidChangePass: 'Xác nhận mật khẩu không trùng khớp',
  kChangePassOK: 'Mật khẩu của bạn\nđã được thay đổi thành công.',
  kTabBarIntro: 'Giới thiệu',
  kTabbarHistory: 'Lịch sử',
  kOnusInfo: 'Số điện thoại hoặc Email đã đăng ký ví ONUS',
  kOnusNotFound: 'Tài khoản Onus không tồn tại',
  kOnusNotFoundOrKYC: 'Tài khoản Onus không tồn tại hoặc chưa KYC',
  kInputOnus: 'Vui lòng nhập tài khoản Onus',
  kNoRank: 'Không xếp hạng',
  kExceededAvailableBalance: 'Số lượng vượt quá số dư khả dụng',
  kFeeTransaction: 'Phí giao dịch: %s',
  kTitleExpired: 'Phiên đăng ký hết hạn',
  kMgsExpired: 'Vui lòng thực hiện lại.',
  kInvalidAccount: 'Tài khoản không tồn tại',
  kSelectSwapCoin: 'Chọn loại tài sản muốn quy đổi',
  kSwapCoin: 'Bạn có chắc chắn muốn quy đổi\n %s sang %s?',
  kCancelSwap: 'Hủy',
  kConfirmSwap: 'Xác nhận quy đổi',
  kSuccessSwap: 'Quy đổi thành công.',
  kConfirmWait: 'Tiếp tục đợi',
  kConfirmCancel: 'Bạn muốn hủy giao dịch?',
  kDesCancel:
      'Nếu bạn đã thanh toán,\nvui lòng đợi hệ thống xác nhận.',
  kTitleCancelDeposit: 'Bạn muốn hủy giao dịch?',
  kPaidDeposit: 'Nếu bạn đã thanh toán',
  kWaitConfirmDeposit: 'vui lòng đợi hệ thống xác nhận.',
  kContinueWait: 'Tiếp tục đợi',
  kPendingDeposit: 'Giao dịch đang được xử lý...',
  kSwapContentSuccess: 'Bạn nhận được',
  kSwapDetailWallet: 'Xem chi tiết ví',
  kSwapPending: 'Tính năng đang tạm khoá\nVui lòng thử lại sau.',
  kPending10s: 'Thực hiện quy đổi sau %s giây\nVui lòng thử lại.',
  kMinHoldExChange: 'Duy trì số dư tối thiểu: %s',
  kMaxExChange: 'Số lượng quy đổi tối đa: %s',
  kAvailableCoin: 'Số dư khả dụng: %s',
  kInvalidAmount: 'Số lượng nhập không chính xác.',
  kSessionGameEnd: 'Phiên giao dịch của bạn đã kết thúc.',
  kEmptyBBC:
      'Bạn không đủ số dư BBC. Vui lòng nạp thêm BBC vào ví trước khi chơi game.',
  kAddSlotSpiner: 'Nhận thêm lượt quay',
  kSatoshi: 'Satoshi',
  kResultSpiner: 'Chúc mừng bạn nhận được',
  kNoHappy: 'Chúc bạn may mắn lần sau',
  kRewardNext: 'Phần Thưởng %s% cho đơn hàng tiếp theo',
  kSatoshiMining: 'Satoshi Mining',
  kEndSatoshi: 'Hết Satoshi để đào',
  kEndEarnSatoshi: 'Hết lượt đào trong ngày',
  kBitLotTitle: 'Con số tài lộc',
  kBitLotWaitResult: 'Chờ kết quả sau',
  kGiftBag: 'Túi quà',
  kRemoveAccount: 'Xác nhận xóa tài khoản',
  kInfoRemoveAccount:
      'Tài khoản của bạn sẽ bị khóa sau 30 ngày kể từ hôm nay, Đăng nhập lại sẽ hủy quá trình này',
};
